/* =========================================================
   LES PANNEAUX — permis voiture
   Visuels : fichiers SVG de Wikimedia Commons (dossier /pan/),
   panneaux réglementaires français, non modifiés.
   Auteurs et licences : voir le pied de page.
   Les textes sont rédigés pour ce site.
   ========================================================= */
'use strict';

const PANNEAUX = [
  /* ============ DANGER ============ */
  { id: 'A1a', cat: 'danger', nom: 'Virage à droite',
    quoi: 'Un virage dangereux vers la droite.',
    faire: 'Ralentir AVANT le virage, se tenir à droite, ne pas doubler.' },
  { id: 'A1b', cat: 'danger', nom: 'Virage à gauche',
    quoi: 'Un virage dangereux vers la gauche.',
    faire: 'Ralentir avant, et se méfier : la visibilité y est souvent plus courte.' },
  { id: 'A1c', cat: 'danger', nom: 'Succession de virages, le premier à droite',
    quoi: 'Plusieurs virages rapprochés.',
    faire: 'Adapter son allure sur toute la section : le dépassement y est très risqué.' },
  { id: 'A1d', cat: 'danger', nom: 'Succession de virages, le premier à gauche',
    quoi: 'Plusieurs virages rapprochés.',
    faire: 'Garder une vitesse régulière plutôt que d\'accélérer entre chaque courbe.' },
  { id: 'A2a', cat: 'danger', nom: 'Cassis ou dos-d\'âne',
    quoi: 'Creux ou bosse marqués sur la chaussée.',
    faire: 'Ralentir : la suspension travaille et la visibilité est coupée un instant.' },
  { id: 'A2b', cat: 'danger', nom: 'Ralentisseur de type dos-d\'âne',
    quoi: 'Un ralentisseur aménagé traverse la chaussée.',
    faire: 'Le franchir doucement, bien perpendiculairement.' },
  { id: 'A3', cat: 'danger', nom: 'Chaussée rétrécie',
    quoi: 'La route se rétrécit des deux côtés.',
    faire: 'Ralentir et se préparer à céder le passage si l\'on ne peut pas croiser.' },
  { id: 'A3a', cat: 'danger', nom: 'Chaussée rétrécie par la droite',
    quoi: 'La voie se resserre du côté droit.',
    faire: 'Anticiper : les véhicules de droite vont devoir se rabattre.' },
  { id: 'A3b', cat: 'danger', nom: 'Chaussée rétrécie par la gauche',
    quoi: 'La voie se resserre du côté gauche.',
    faire: 'Rester à droite et laisser la place à ceux qui se rabattent.' },
  { id: 'A4', cat: 'danger', nom: 'Chaussée glissante',
    quoi: 'Risque de glissance : pluie, verglas, gravillons, boue.',
    faire: 'Réduire la vitesse, éviter freinages et coups de volant brusques.' },
  { id: 'A6', cat: 'danger', nom: 'Pont mobile',
    quoi: 'Un pont qui se lève ou pivote.',
    faire: 'Être prêt à s\'arrêter : les feux et barrières peuvent se déclencher.' },
  { id: 'A7', cat: 'danger', nom: 'Passage à niveau avec barrières',
    quoi: 'Croisement d\'une voie ferrée, protégé par des barrières.',
    faire: 'Ne jamais s\'engager si l\'on ne peut pas dégager de l\'autre côté.' },
  { id: 'A8', cat: 'danger', nom: 'Passage à niveau sans barrières',
    quoi: 'Voie ferrée non protégée.',
    faire: 'Ralentir fortement, regarder des deux côtés, écouter. Le train ne peut pas freiner.' },
  { id: 'A9', cat: 'danger', nom: 'Traversée de voies de tramway',
    quoi: 'Des rails de tramway coupent la route.',
    faire: 'Le tramway est prioritaire et ne peut pas dévier. Ne jamais rester sur les rails.' },
  { id: 'A13a', cat: 'danger', nom: 'Endroit fréquenté par des enfants',
    quoi: 'École, sortie de classe ou aire de jeux à proximité.',
    faire: 'Lever le pied et surveiller les trottoirs : un enfant traverse sans regarder.' },
  { id: 'A13b', cat: 'danger', nom: 'Passage pour piétons',
    quoi: 'Un passage protégé est annoncé plus loin.',
    faire: 'Ralentir et être prêt à s\'arrêter.' },
  { id: 'A14', cat: 'danger', nom: 'Autres dangers',
    quoi: 'Un danger qui n\'a pas de panneau propre.',
    faire: 'Lire le panonceau sous le panneau : c\'est lui qui précise de quoi il s\'agit.' },
  { id: 'A15a1', cat: 'danger', nom: 'Passage d\'animaux domestiques',
    quoi: 'Troupeaux, bétail traversant ou longeant la route.',
    faire: 'Ralentir, ne pas klaxonner : un troupeau qui s\'affole est plus dangereux.' },
  { id: 'A15b', cat: 'danger', nom: 'Passage d\'animaux sauvages',
    quoi: 'Passage fréquent de gibier.',
    faire: 'Ralentir à l\'aube et au crépuscule. Un animal est rarement seul.' },
  { id: 'A16', cat: 'danger', nom: 'Descente dangereuse',
    quoi: 'Forte pente descendante, le pourcentage est indiqué.',
    faire: 'Rétrograder et utiliser le frein moteur, sans rester appuyé sur la pédale.' },
  { id: 'A17', cat: 'danger', nom: 'Annonce de feux tricolores',
    quoi: 'Une signalisation lumineuse arrive.',
    faire: 'Anticiper le freinage : le feu peut passer au rouge avant votre arrivée.' },
  { id: 'A18', cat: 'danger', nom: 'Circulation dans les deux sens',
    quoi: 'Fin d\'une chaussée à sens unique : on va croiser des véhicules.',
    faire: 'Serrer à droite et redoubler d\'attention avant tout dépassement.' },
  { id: 'A19', cat: 'danger', nom: 'Chute de pierres',
    quoi: 'Risque d\'éboulement ou de pierres sur la chaussée.',
    faire: 'Ralentir et surveiller le sol : une pierre peut être déjà tombée dans un virage.' },
  { id: 'A20', cat: 'danger', nom: 'Débouché sur un quai ou une berge',
    quoi: 'La route se termine au bord de l\'eau.',
    faire: 'Ralentir très tôt : il n\'y a parfois aucune barrière.' },
  { id: 'A21', cat: 'danger', nom: 'Débouché de cyclistes',
    quoi: 'Des cyclistes vont s\'insérer ou traverser.',
    faire: 'Contrôler l\'angle mort et laisser 1 m d\'écart en ville, 1,50 m hors agglomération.' },
  { id: 'A23', cat: 'danger', nom: 'Survol par des aéronefs',
    quoi: 'Avions à très basse altitude à proximité d\'un aérodrome.',
    faire: 'Ne pas se laisser surprendre par le bruit ou l\'ombre.' },
  { id: 'A24', cat: 'danger', nom: 'Vent latéral',
    quoi: 'Vent traversier violent, souvent sur un pont ou en plaine.',
    faire: 'Tenir le volant fermement à deux mains et ralentir. Attention en doublant un camion.' },

  /* ============ SIGNALISATION TEMPORAIRE ============ */
  { id: 'AK5', cat: 'danger', nom: 'Travaux',
    quoi: 'Chantier sur ou au bord de la chaussée.',
    faire: 'Ralentir. La signalisation temporaire prime toujours sur la permanente.' },
  { id: 'AK3', cat: 'danger', nom: 'Chaussée rétrécie (temporaire)',
    quoi: 'Rétrécissement provisoire lié à un chantier.',
    faire: 'Se rabattre tôt, en fermeture éclair, sans forcer le passage.' },
  { id: 'AK14', cat: 'danger', nom: 'Autres dangers (temporaire)',
    quoi: 'Danger temporaire précisé par un panonceau.',
    faire: 'Le fond jaune signale toujours du provisoire : redoubler d\'attention.' },
  { id: 'AK17', cat: 'danger', nom: 'Feux temporaires',
    quoi: 'Des feux provisoires règlent un alternat de circulation.',
    faire: 'Attendre le vert même si la voie semble libre : un véhicule peut arriver en face.' },
  { id: 'AK22', cat: 'danger', nom: 'Projection de gravillons',
    quoi: 'Revêtement fraîchement gravillonné.',
    faire: 'Ralentir nettement et augmenter les distances : les projections cassent les pare-brise.' },

  /* ============ PRIORITÉ ============ */
  { id: 'AB1', cat: 'priorite', nom: 'Intersection à priorité à droite',
    quoi: 'Carrefour où la priorité à droite s\'applique.',
    faire: 'Céder le passage à tout véhicule arrivant de sa droite, même d\'une petite rue.' },
  { id: 'AB2', cat: 'priorite', nom: 'Priorité à la prochaine intersection',
    quoi: 'Vous êtes prioritaire au prochain carrefour seulement.',
    faire: 'Rester prudent : les autres ne respectent pas toujours leur cédez-le-passage.' },
  { id: 'AB3a', cat: 'priorite', nom: 'Cédez le passage',
    quoi: 'Laisser passer les véhicules circulant sur la route abordée.',
    faire: 'On peut passer sans s\'arrêter si la voie est libre — mais on doit pouvoir s\'arrêter.' },
  { id: 'AB4', cat: 'priorite', nom: 'Stop',
    quoi: 'Arrêt absolu et obligatoire à la ligne.',
    faire: 'Les roues doivent s\'immobiliser complètement, même si la route est vide.' },
  { id: 'AB5', cat: 'priorite', nom: 'Stop à 150 m',
    quoi: 'Annonce d\'un stop un peu plus loin.',
    faire: 'Commencer à ralentir dès maintenant.' },
  { id: 'AB6', cat: 'priorite', nom: 'Route prioritaire',
    quoi: 'On circule sur une route prioritaire.',
    faire: 'La priorité à droite ne s\'applique plus aux intersections suivantes.' },
  { id: 'AB7', cat: 'priorite', nom: 'Fin de route prioritaire',
    quoi: 'La route cesse d\'être prioritaire.',
    faire: 'On repasse aux règles habituelles : attention à la priorité à droite.' },
  { id: 'AB25', cat: 'priorite', nom: 'Carrefour à sens giratoire',
    quoi: 'Un rond-point est annoncé.',
    faire: 'Presque toujours accompagné d\'un cédez-le-passage : ceux qui tournent sont prioritaires.' },

  /* ============ INTERDICTION ============ */
  { id: 'B0', cat: 'interdiction', nom: 'Circulation interdite à tout véhicule',
    quoi: 'Accès interdit dans les deux sens.',
    faire: 'Lire le panonceau : souvent « sauf riverains » ou « sauf livraisons ».' },
  { id: 'B1', cat: 'interdiction', nom: 'Sens interdit',
    quoi: 'Accès interdit à tous les véhicules dans ce sens.',
    faire: 'Ne jamais s\'engager : on arriverait face à la circulation.' },
  { id: 'B2a', cat: 'interdiction', nom: 'Interdiction de tourner à gauche',
    quoi: 'Défense de tourner à gauche à la prochaine intersection.',
    faire: 'Prévoir un autre itinéraire : souvent trois « à droite » valent un « à gauche ».' },
  { id: 'B2b', cat: 'interdiction', nom: 'Interdiction de faire demi-tour',
    quoi: 'Le demi-tour est interdit jusqu\'à la prochaine intersection.',
    faire: 'Continuer et chercher un endroit prévu pour se retourner.' },
  { id: 'B3', cat: 'interdiction', nom: 'Dépassement interdit',
    quoi: 'Interdiction de dépasser tout véhicule à moteur.',
    faire: 'Rester dans sa file. Les deux-roues restent doublables.' },
  { id: 'B3a', cat: 'interdiction', nom: 'Dépassement interdit aux camions',
    quoi: 'Interdiction visant les poids lourds de plus de 3,5 t.',
    faire: 'En voiture, le dépassement reste autorisé.' },
  { id: 'B4', cat: 'interdiction', nom: 'Arrêt à la douane',
    quoi: 'Arrêt obligatoire au poste de douane.',
    faire: 'S\'arrêter et attendre l\'autorisation de repartir.' },
  { id: 'B5a', cat: 'interdiction', nom: 'Halte — gendarmerie',
    quoi: 'Arrêt obligatoire au poste de contrôle.',
    faire: 'S\'arrêter, couper le moteur si demandé, présenter ses papiers.' },
  { id: 'B5b', cat: 'interdiction', nom: 'Halte — police',
    quoi: 'Arrêt obligatoire au poste de contrôle.',
    faire: 'Même consigne : s\'arrêter et rester à disposition.' },
  { id: 'B6a1', cat: 'interdiction', nom: 'Stationnement interdit',
    quoi: 'Interdiction de stationner. L\'arrêt, lui, reste possible.',
    faire: 'On peut s\'immobiliser pour laisser monter ou descendre, sans quitter le véhicule.' },
  { id: 'B6d', cat: 'interdiction', nom: 'Arrêt et stationnement interdits',
    quoi: 'Ni arrêt, ni stationnement.',
    faire: 'On ne s\'immobilise pas du tout, même moteur tournant et conducteur au volant.' },
  { id: 'B7a', cat: 'interdiction', nom: 'Interdit aux véhicules à moteur',
    quoi: 'Voitures et motos interdites.',
    faire: 'Piétons et cyclistes peuvent en général passer.' },
  { id: 'B8', cat: 'interdiction', nom: 'Interdit aux camions',
    quoi: 'Accès interdit aux poids lourds.',
    faire: 'Le tonnage limite est parfois précisé sur un panonceau.' },
  { id: 'B9a', cat: 'interdiction', nom: 'Interdit aux piétons',
    quoi: 'Voie interdite à la circulation des piétons.',
    faire: 'Typique des voies rapides : on n\'y marche jamais, même en panne.' },
  { id: 'B9b', cat: 'interdiction', nom: 'Interdit aux cycles',
    quoi: 'Accès interdit aux vélos.',
    faire: 'Chercher l\'itinéraire cyclable parallèle.' },
  { id: 'B11', cat: 'interdiction', nom: 'Largeur limitée',
    quoi: 'Passage interdit au-delà de la largeur indiquée.',
    faire: 'Compter les rétroviseurs et le chargement, pas seulement la carrosserie.' },
  { id: 'B12', cat: 'interdiction', nom: 'Hauteur limitée',
    quoi: 'Passage interdit au-delà de la hauteur indiquée.',
    faire: 'Penser aux barres de toit, coffre ou vélos sur le toit.' },
  { id: 'B13', cat: 'interdiction', nom: 'Poids limité',
    quoi: 'Interdit aux véhicules dépassant le poids indiqué.',
    faire: 'Il s\'agit du poids total en charge, chargement compris.' },
  { id: 'B1430', cat: 'interdiction', nom: 'Limitation à 30 km/h',
    quoi: 'Vitesse maximale : 30 km/h.',
    faire: 'Fréquent en centre-ville et aux abords des écoles.' },
  { id: 'B1450', cat: 'interdiction', nom: 'Limitation à 50 km/h',
    quoi: 'Vitesse maximale : 50 km/h.',
    faire: 'La limite court jusqu\'au prochain panneau ou à la prochaine intersection.' },
  { id: 'B1470', cat: 'interdiction', nom: 'Limitation à 70 km/h',
    quoi: 'Vitesse maximale : 70 km/h.',
    faire: 'Souvent posé à l\'approche d\'une zone dangereuse ou d\'une agglomération.' },
  { id: 'B1480', cat: 'interdiction', nom: 'Limitation à 80 km/h',
    quoi: 'Vitesse maximale : 80 km/h.',
    faire: 'C\'est la limite courante des routes à double sens sans séparateur central.' },
  { id: 'B1490', cat: 'interdiction', nom: 'Limitation à 90 km/h',
    quoi: 'Vitesse maximale : 90 km/h.',
    faire: 'Certains départements ont relevé leurs routes à 90 : c\'est le panneau qui fait foi.' },
  { id: 'B14110', cat: 'interdiction', nom: 'Limitation à 110 km/h',
    quoi: 'Vitesse maximale : 110 km/h.',
    faire: 'Typique des voies rapides à chaussées séparées. 100 sous la pluie.' },
  { id: 'B14130', cat: 'interdiction', nom: 'Limitation à 130 km/h',
    quoi: 'Vitesse maximale : 130 km/h.',
    faire: 'Autoroute par temps sec. 110 dès qu\'il pleut.' },
  { id: 'B15', cat: 'interdiction', nom: 'Cédez le passage à la circulation en sens inverse',
    quoi: 'Dans un passage étroit, l\'autre sens est prioritaire.',
    faire: 'S\'arrêter avant le rétrécissement et laisser passer.' },
  { id: 'B18a', cat: 'interdiction', nom: 'Interdit aux transports de matières explosives',
    quoi: 'Restriction visant certains transports dangereux.',
    faire: 'Sans effet pour une voiture particulière.' },
  { id: 'B18c', cat: 'interdiction', nom: 'Interdit aux transports de matières polluantes',
    quoi: 'Restriction visant les transports pouvant polluer l\'eau.',
    faire: 'Fréquent près des captages et des réserves d\'eau potable.' },
  { id: 'B26', cat: 'interdiction', nom: 'Équipements hivernaux obligatoires',
    quoi: 'Chaînes ou pneus hiver exigés.',
    faire: 'Sans équipement, on ne s\'engage pas : en montagne, la route peut être fermée.' },
  { id: 'B27a', cat: 'interdiction', nom: 'Voie réservée aux autobus',
    quoi: 'Couloir réservé aux transports en commun.',
    faire: 'Ne pas y circuler ni s\'y arrêter, même une minute.' },
  { id: 'B29', cat: 'interdiction', nom: 'Allumage des feux obligatoire',
    quoi: 'Feux de croisement obligatoires sur la section.',
    faire: 'Fréquent avant un tunnel : allumer avant d\'entrer, pas dedans.' },
  { id: 'B31', cat: 'interdiction', nom: 'Fin de toutes les interdictions',
    quoi: 'Toutes les interdictions précédentes cessent.',
    faire: 'On revient aux règles générales de la route où l\'on se trouve.' },
  { id: 'B34', cat: 'interdiction', nom: 'Fin d\'interdiction de dépasser',
    quoi: 'Le dépassement redevient autorisé.',
    faire: 'Autorisé ne veut pas dire possible : vérifier la visibilité et le marquage au sol.' },
  { id: 'B40', cat: 'interdiction', nom: 'Fin de piste cyclable obligatoire',
    quoi: 'Les cyclistes ne sont plus tenus d\'emprunter la piste.',
    faire: 'En voiture : s\'attendre à les retrouver sur la chaussée.' },
  { id: 'B49', cat: 'interdiction', nom: 'Fin d\'allumage des feux',
    quoi: 'L\'obligation d\'allumer les feux cesse.',
    faire: 'Les feux de jour peuvent rester allumés, ça ne gêne personne.' },
  { id: 'B54', cat: 'interdiction', nom: 'Zone piétonne',
    quoi: 'Zone réservée aux piétons.',
    faire: 'Circulation motorisée interdite sauf autorisation. Le piéton y est chez lui.' },

  /* ============ OBLIGATION ============ */
  { id: 'B21-1', cat: 'obligation', nom: 'Direction obligatoire : à droite',
    quoi: 'Il faut tourner à droite.',
    faire: 'Se placer et mettre son clignotant à l\'avance.' },
  { id: 'B21-2', cat: 'obligation', nom: 'Direction obligatoire : à gauche',
    quoi: 'Il faut tourner à gauche.',
    faire: 'Vérifier ses rétroviseurs et l\'angle mort avant de se déporter.' },
  { id: 'B21b', cat: 'obligation', nom: 'Direction obligatoire : tout droit',
    quoi: 'Il faut continuer tout droit.',
    faire: 'Ni à gauche, ni à droite au prochain carrefour.' },
  { id: 'B21c1', cat: 'obligation', nom: 'Obligation de tourner à droite',
    quoi: 'La seule direction permise est à droite, avant le panneau.',
    faire: 'Ne pas confondre avec le contournement : ici on change de rue.' },
  { id: 'B21d1', cat: 'obligation', nom: 'Tout droit ou à droite',
    quoi: 'Deux directions autorisées, pas la gauche.',
    faire: 'Choisir sa voie tôt et signaler son intention.' },
  { id: 'B21e', cat: 'obligation', nom: 'À droite ou à gauche',
    quoi: 'Il faut tourner, d\'un côté ou de l\'autre.',
    faire: 'Continuer tout droit est interdit : souvent une rue barrée en face.' },
  { id: 'B21a1', cat: 'obligation', nom: 'Contournement obligatoire par la droite',
    quoi: 'L\'obstacle doit être contourné par la droite.',
    faire: 'Suivre la flèche : passer de l\'autre côté est dangereux et sanctionné.' },
  { id: 'B22a', cat: 'obligation', nom: 'Piste cyclable obligatoire',
    quoi: 'Piste réservée aux cyclistes, qui doivent l\'emprunter.',
    faire: 'En voiture : ne jamais y circuler, ni s\'y arrêter, ni s\'y garer.' },
  { id: 'B22b', cat: 'obligation', nom: 'Chemin obligatoire pour piétons',
    quoi: 'Cheminement réservé aux piétons.',
    faire: 'Interdit aux véhicules.' },

  /* ============ INDICATION ============ */
  { id: 'C1a', cat: 'indication', nom: 'Stationnement autorisé',
    quoi: 'Emplacement où le stationnement est permis.',
    faire: 'Lire les panonceaux : durée, jours, places réservées.' },
  { id: 'C1b', cat: 'indication', nom: 'Stationnement payant',
    quoi: 'Stationnement soumis à paiement.',
    faire: 'Prendre le ticket et le rendre visible derrière le pare-brise.' },
  { id: 'C3', cat: 'indication', nom: 'Poste d\'appel d\'urgence',
    quoi: 'Borne d\'appel reliée aux secours.',
    faire: 'Sur autoroute, préférer la borne au téléphone : elle localise l\'appel exactement.' },
  { id: 'C5', cat: 'indication', nom: 'Station de taxis',
    quoi: 'Emplacement réservé aux taxis.',
    faire: 'Ni arrêt ni stationnement pour les autres véhicules.' },
  { id: 'C6', cat: 'indication', nom: 'Arrêt d\'autobus',
    quoi: 'Emplacement d\'arrêt des transports en commun.',
    faire: 'Ne pas s\'y arrêter, et faciliter la réinsertion du bus en agglomération.' },
  { id: 'C12', cat: 'indication', nom: 'Circulation à sens unique',
    quoi: 'On circule dans un seul sens, celui de la flèche.',
    faire: 'Toute la largeur est utilisable, mais revenir en arrière est interdit.' },
  { id: 'C13a', cat: 'indication', nom: 'Impasse',
    quoi: 'La voie ne débouche sur aucune autre.',
    faire: 'Il faudra faire demi-tour : à éviter avec une remorque.' },
  { id: 'C13b', cat: 'indication', nom: 'Impasse avec issue piétonne',
    quoi: 'Sans issue pour les voitures, mais un passage existe à pied ou à vélo.',
    faire: 'Ne pas s\'y engager en voiture en espérant passer.' },
  { id: 'C18', cat: 'indication', nom: 'Priorité sur la circulation en sens inverse',
    quoi: 'Dans un passage étroit, vous êtes prioritaire.',
    faire: 'Passer en premier, mais sans forcer : vérifier que l\'autre s\'arrête.' },
  { id: 'C20a', cat: 'indication', nom: 'Passage pour piétons',
    quoi: 'Emplacement d\'un passage protégé.',
    faire: 'Céder le passage au piéton engagé ou qui manifeste l\'intention de traverser.' },
  { id: 'C20c', cat: 'indication', nom: 'Surélévation de chaussée',
    quoi: 'Plateau ou passage piéton surélevé.',
    faire: 'Ralentir avant, pas dessus.' },
  { id: 'C23', cat: 'indication', nom: 'Entrée de commune',
    quoi: 'Panneau nominatif d\'entrée de localité.',
    faire: 'Attention : seul le panneau d\'agglomération à fond blanc impose le 50.' },
  { id: 'C24a', cat: 'indication', nom: 'Affectation des voies',
    quoi: 'Indique à quoi sert chaque voie de circulation.',
    faire: 'Se placer tôt : changer au dernier moment provoque les accrochages.' },
  { id: 'C25a', cat: 'indication', nom: 'Franchissement de frontière',
    quoi: 'Entrée dans un autre pays de l\'Union européenne.',
    faire: 'Les limitations changent : les lire dès les premiers panneaux.' },
  { id: 'C26a', cat: 'indication', nom: 'Réduction du nombre de voies',
    quoi: 'Une voie disparaît plus loin.',
    faire: 'Se rabattre en fermeture éclair, chacun son tour, sans accélérer pour doubler.' },
  { id: 'C27', cat: 'indication', nom: 'Ralentisseur',
    quoi: 'Un ralentisseur est présent sur la chaussée.',
    faire: 'Le franchir au pas : la limitation associée est en général 30 km/h.' },
  { id: 'C29a', cat: 'indication', nom: 'Affectation de voies par direction',
    quoi: 'Chaque flèche indique où mène sa voie.',
    faire: 'Lire tôt et se placer : c\'est ce qui évite les manœuvres de dernière seconde.' },
  { id: 'C50', cat: 'indication', nom: 'Arrêt autorisé sur trottoir',
    quoi: 'Autorisation exceptionnelle de s\'arrêter sur le trottoir.',
    faire: 'Laisser toujours le passage libre pour les piétons et les poussettes.' },
  { id: 'C62', cat: 'indication', nom: 'Stationnement avec horodateur',
    quoi: 'Emplacement payant avec appareil de paiement.',
    faire: 'Le ticket doit être visible, sinon c\'est verbalisé même si vous avez payé.' },
  { id: 'C64a', cat: 'indication', nom: 'Créneau de dépassement',
    quoi: 'Une voie supplémentaire permet de doubler.',
    faire: 'Doubler tôt : la voie se referme toujours plus vite qu\'on ne le croit.' },
  { id: 'C107', cat: 'indication', nom: 'Route à accès réglementé',
    quoi: 'Voie réservée aux véhicules à moteur.',
    faire: 'Interdite aux piétons, cyclistes et engins lents. Vitesse en général 110.' },
  { id: 'C108', cat: 'indication', nom: 'Fin de route à accès réglementé',
    quoi: 'Les règles de la voie rapide cessent.',
    faire: 'On peut retrouver des carrefours, des piétons et des vélos.' },
  { id: 'C111', cat: 'indication', nom: 'Tunnel',
    quoi: 'Entrée d\'un tunnel.',
    faire: 'Allumer les feux, retirer les lunettes de soleil, garder 2 s ou 150 m d\'écart.' },
  { id: 'C112', cat: 'indication', nom: 'Sortie de tunnel',
    quoi: 'Fin du tunnel.',
    faire: 'Attention à l\'éblouissement en sortant, et au vent latéral.' },
  { id: 'C113', cat: 'indication', nom: 'Piste conseillée aux cyclistes',
    quoi: 'Aménagement recommandé, mais non obligatoire.',
    faire: 'À la différence du panneau rond bleu, le cycliste garde le choix.' },
  { id: 'C115', cat: 'indication', nom: 'Voie verte',
    quoi: 'Voie réservée aux piétons, cyclistes et cavaliers.',
    faire: 'Interdite aux véhicules à moteur.' },
  { id: 'C116', cat: 'indication', nom: 'Fin de voie verte',
    quoi: 'La voie verte se termine.',
    faire: 'Les usagers vont rejoindre la route : redoubler d\'attention.' },
  { id: 'C207', cat: 'indication', nom: 'Entrée d\'autoroute',
    quoi: 'Début de l\'autoroute et de ses règles particulières.',
    faire: 'Maxi 130 (110 sous la pluie). Arrêt interdit sauf urgence sur la bande.' },
  { id: 'C208', cat: 'indication', nom: 'Fin d\'autoroute',
    quoi: 'Les règles de l\'autoroute cessent de s\'appliquer.',
    faire: 'Ralentir : on retrouve carrefours, piétons et vitesses plus basses.' },
  { id: 'EB10', cat: 'indication', nom: 'Entrée d\'agglomération',
    quoi: 'On entre en ville. Le panneau ne montre aucun chiffre.',
    faire: 'La vitesse passe automatiquement à 50 km/h, sans autre panneau.' },
  { id: 'EB20', cat: 'indication', nom: 'Sortie d\'agglomération',
    quoi: 'On quitte la ville. Le nom est barré.',
    faire: 'La limite de l\'agglomération cesse : on reprend la vitesse de la route.' }
];

const CATEGORIES = [
  { id: 'danger', nom: 'Danger', forme: 'Triangle à bord rouge (jaune si travaux)',
    regle: 'Ils annoncent un risque. Placés à 150 m environ hors agglomération, 50 m en ville. Le fond jaune signale du temporaire, et il prime sur la signalisation permanente.' },
  { id: 'priorite', nom: 'Priorité', forme: 'Formes propres à chacun',
    regle: 'Ils disent qui passe en premier. En l\'absence de tout panneau et de tout marquage : priorité à droite.' },
  { id: 'interdiction', nom: 'Interdiction', forme: 'Disque à bord rouge',
    regle: 'Ils interdisent. Valables jusqu\'au panneau de fin, à la prochaine intersection, ou selon ce que dit le panonceau.' },
  { id: 'obligation', nom: 'Obligation', forme: 'Disque bleu',
    regle: 'Ils imposent un comportement. Retenez la règle : le bleu commande, le rouge interdit.' },
  { id: 'indication', nom: 'Indication', forme: 'Carré ou rectangle bleu',
    regle: 'Ils renseignent sans rien imposer — sauf quand ils créent un régime particulier (autoroute, sens unique, agglomération).' }
];
