/* =========================================================
   LES PANNEAUX
   Les visuels sont les vrais panneaux réglementaires français,
   récupérés sur Wikimedia Commons (fichiers SVG dans /pan/).
   Auteurs et licences : voir CREDITS plus bas et le pied de page.
   Les textes « ce que ça veut dire / ce qu'il faut faire » sont
   rédigés pour ce site.
   ========================================================= */
'use strict';

const PANNEAUX = [
  /* ================= DANGER ================= */
  { id: 'A1a', cat: 'danger', nom: 'Virage à droite',
    quoi: 'Un virage dangereux vers la droite.',
    faire: 'Ralentir AVANT le virage, se tenir à droite, ne pas doubler.' },
  { id: 'A1c', cat: 'danger', nom: 'Succession de virages',
    quoi: 'Plusieurs virages rapprochés, le premier vers la droite.',
    faire: 'Adapter son allure sur toute la section : le dépassement y est très risqué.' },
  { id: 'A2a', cat: 'danger', nom: 'Cassis ou dos-d\'âne',
    quoi: 'La chaussée présente une bosse ou un creux marqué.',
    faire: 'Ralentir franchement : la visibilité et la tenue de route sont réduites.' },
  { id: 'A3', cat: 'danger', nom: 'Chaussée rétrécie',
    quoi: 'La route devient plus étroite, d\'un côté ou des deux.',
    faire: 'Ralentir et se préparer à céder le passage si l\'on ne peut pas croiser.' },
  { id: 'A4', cat: 'danger', nom: 'Chaussée glissante',
    quoi: 'Risque de glissance : pluie, verglas, gravillons, boue.',
    faire: 'Réduire la vitesse, éviter freinages et coups de volant brusques.' },
  { id: 'A13a', cat: 'danger', nom: 'Endroit fréquenté par des enfants',
    quoi: 'École, sortie de classe ou aire de jeux à proximité.',
    faire: 'Lever le pied et surveiller les trottoirs : un enfant peut surgir sans regarder.' },
  { id: 'A13b', cat: 'danger', nom: 'Passage pour piétons',
    quoi: 'Un passage protégé est annoncé plus loin.',
    faire: 'Ralentir et être prêt à s\'arrêter : le piéton qui traverse est prioritaire.' },
  { id: 'A14', cat: 'danger', nom: 'Autres dangers',
    quoi: 'Un danger qui n\'a pas de panneau propre.',
    faire: 'Lire le panonceau sous le panneau : c\'est lui qui précise de quoi il s\'agit.' },
  { id: 'A15b', cat: 'danger', nom: 'Traversée d\'animaux sauvages',
    quoi: 'Passage fréquent de gibier.',
    faire: 'Ralentir, surtout à l\'aube et au crépuscule. Un animal est rarement seul.' },
  { id: 'A16', cat: 'danger', nom: 'Descente dangereuse',
    quoi: 'Forte pente descendante, le pourcentage est indiqué.',
    faire: 'Rétrograder et utiliser le frein moteur, ne pas rester appuyé sur la pédale.' },
  { id: 'A17', cat: 'danger', nom: 'Annonce de feux tricolores',
    quoi: 'Une signalisation lumineuse est annoncée.',
    faire: 'Anticiper le freinage : le feu peut passer au rouge avant votre arrivée.' },
  { id: 'A18', cat: 'danger', nom: 'Circulation dans les deux sens',
    quoi: 'Fin d\'une chaussée à sens unique : on va croiser des véhicules.',
    faire: 'Serrer à droite et redoubler d\'attention avant tout dépassement.' },
  { id: 'AK5', cat: 'danger', nom: 'Travaux',
    quoi: 'Chantier sur ou au bord de la chaussée.',
    faire: 'Ralentir. La signalisation temporaire prime toujours sur la permanente.' },

  /* ================= INTERDICTION ================= */
  { id: 'B0', cat: 'interdiction', nom: 'Circulation interdite à tout véhicule',
    quoi: 'Accès interdit dans les deux sens.',
    faire: 'Chercher un autre itinéraire. Souvent complété d\'un panonceau « sauf riverains ».' },
  { id: 'B1', cat: 'interdiction', nom: 'Sens interdit',
    quoi: 'Accès interdit à tous les véhicules dans ce sens.',
    faire: 'Ne jamais s\'engager : on arriverait face à la circulation.' },
  { id: 'B3', cat: 'interdiction', nom: 'Dépassement interdit',
    quoi: 'Interdiction de dépasser tout véhicule à moteur.',
    faire: 'Rester dans sa file jusqu\'au panneau de fin. Les deux-roues restent doublables.' },
  { id: 'B1430', cat: 'interdiction', nom: 'Limitation à 30 km/h',
    quoi: 'Vitesse maximale autorisée : 30 km/h.',
    faire: 'Typique des centres-villes et abords d\'école. Valable jusqu\'au prochain panneau.' },
  { id: 'B1450', cat: 'interdiction', nom: 'Limitation à 50 km/h',
    quoi: 'Vitesse maximale autorisée : 50 km/h.',
    faire: 'La limite court jusqu\'au prochain panneau ou à la prochaine intersection.' },
  { id: 'B6a1', cat: 'interdiction', nom: 'Stationnement interdit',
    quoi: 'Interdiction de stationner. L\'arrêt, lui, reste possible.',
    faire: 'On peut s\'immobiliser pour laisser monter ou descendre, sans quitter le véhicule.' },
  { id: 'B6d', cat: 'interdiction', nom: 'Arrêt et stationnement interdits',
    quoi: 'Ni arrêt, ni stationnement.',
    faire: 'On ne s\'immobilise pas du tout, même moteur tournant et conducteur au volant.' },
  { id: 'B31', cat: 'interdiction', nom: 'Fin de toutes les interdictions',
    quoi: 'Toutes les interdictions précédentes cessent.',
    faire: 'On revient aux règles générales de la route où l\'on se trouve.' },

  /* ================= OBLIGATION ================= */
  { id: 'B21-1', cat: 'obligation', nom: 'Direction obligatoire : à droite',
    quoi: 'Il faut tourner à droite.',
    faire: 'Se placer et mettre son clignotant à l\'avance.' },
  { id: 'B21-2', cat: 'obligation', nom: 'Direction obligatoire : à gauche',
    quoi: 'Il faut tourner à gauche.',
    faire: 'Vérifier ses rétroviseurs et l\'angle mort avant de se déporter.' },
  { id: 'B21a1', cat: 'obligation', nom: 'Contournement obligatoire par la droite',
    quoi: 'L\'obstacle doit être contourné par la droite.',
    faire: 'Suivre la flèche : passer de l\'autre côté est une infraction, et dangereux.' },
  { id: 'B22a', cat: 'obligation', nom: 'Piste cyclable obligatoire',
    quoi: 'Piste réservée aux cyclistes, qui doivent l\'emprunter.',
    faire: 'En voiture : ne jamais y circuler, ni s\'y arrêter, ni s\'y garer.' },

  /* ================= PRIORITÉ ================= */
  { id: 'AB4', cat: 'priorite', nom: 'Stop',
    quoi: 'Arrêt absolu et obligatoire à la ligne.',
    faire: 'Les roues doivent s\'immobiliser complètement, même si la route est vide.' },
  { id: 'AB3a', cat: 'priorite', nom: 'Cédez le passage',
    quoi: 'Laisser passer les véhicules circulant sur la route abordée.',
    faire: 'On peut passer sans s\'arrêter si la voie est libre — mais on doit pouvoir s\'arrêter.' },
  { id: 'AB6', cat: 'priorite', nom: 'Route prioritaire',
    quoi: 'On circule sur une route prioritaire.',
    faire: 'La priorité à droite ne s\'applique plus aux intersections suivantes.' },
  { id: 'AB7', cat: 'priorite', nom: 'Fin de route prioritaire',
    quoi: 'La route cesse d\'être prioritaire.',
    faire: 'On repasse aux règles habituelles : attention à la priorité à droite.' },
  { id: 'AB1', cat: 'priorite', nom: 'Intersection à priorité à droite',
    quoi: 'Carrefour où la priorité à droite s\'applique.',
    faire: 'Céder le passage à tout véhicule arrivant de sa droite, même une petite rue.' },
  { id: 'AB2', cat: 'priorite', nom: 'Priorité à la prochaine intersection',
    quoi: 'Vous êtes prioritaire au prochain carrefour seulement.',
    faire: 'Rester prudent : les autres ne respectent pas toujours leur cédez-le-passage.' },

  /* ================= INDICATION ================= */
  { id: 'C20a', cat: 'indication', nom: 'Passage pour piétons',
    quoi: 'Emplacement d\'un passage protégé.',
    faire: 'Céder le passage à tout piéton engagé ou manifestant l\'intention de traverser.' },
  { id: 'C1a', cat: 'indication', nom: 'Stationnement autorisé',
    quoi: 'Emplacement où le stationnement est permis.',
    faire: 'Lire les panonceaux : durée, jours, zone payante, places réservées.' },
  { id: 'C13a', cat: 'indication', nom: 'Impasse',
    quoi: 'La voie ne débouche sur aucune autre.',
    faire: 'Il faudra faire demi-tour : à éviter avec une remorque ou un grand véhicule.' },
  { id: 'C12', cat: 'indication', nom: 'Circulation à sens unique',
    quoi: 'On circule dans un seul sens, celui de la flèche.',
    faire: 'Toute la largeur est utilisable, mais revenir en arrière est interdit.' },
  { id: 'C24a', cat: 'indication', nom: 'Affectation des voies',
    quoi: 'Indique à quoi sert chaque voie de circulation.',
    faire: 'Se placer tôt sur la bonne voie : changer au dernier moment crée les accrochages.' },
  { id: 'C107', cat: 'indication', nom: 'Route à accès réglementé',
    quoi: 'Voie réservée aux véhicules à moteur, sans les règles complètes de l\'autoroute.',
    faire: 'Interdite aux piétons, cyclistes et engins lents. Vitesse en général 110.' },
  { id: 'C111', cat: 'indication', nom: 'Tunnel',
    quoi: 'Entrée d\'un tunnel.',
    faire: 'Allumer les feux, retirer les lunettes de soleil, garder 2 s ou 150 m d\'écart.' },
  { id: 'C207', cat: 'indication', nom: 'Entrée d\'autoroute',
    quoi: 'Début de l\'autoroute et de ses règles particulières.',
    faire: 'Maxi 130 (110 sous la pluie). Arrêt interdit sauf urgence sur la bande.' },
  { id: 'C208', cat: 'indication', nom: 'Fin d\'autoroute',
    quoi: 'Les règles de l\'autoroute cessent de s\'appliquer.',
    faire: 'Ralentir : on retrouve des carrefours, des piétons et des vitesses plus basses.' }
];

const CATEGORIES = [
  { id: 'danger', nom: 'Danger', forme: 'Triangle à bord rouge',
    regle: 'Ils annoncent un risque. Placés à 150 m environ hors agglomération, 50 m en ville.' },
  { id: 'interdiction', nom: 'Interdiction', forme: 'Disque à bord rouge',
    regle: 'Ils interdisent. Valables jusqu\'au panneau de fin, à la prochaine intersection, ou selon le panonceau.' },
  { id: 'obligation', nom: 'Obligation', forme: 'Disque bleu',
    regle: 'Ils imposent un comportement. Retenez : le bleu commande, le rouge interdit.' },
  { id: 'priorite', nom: 'Priorité', forme: 'Formes propres à chacun',
    regle: 'Ils disent qui passe en premier. En l\'absence de tout panneau : priorité à droite.' },
  { id: 'indication', nom: 'Indication', forme: 'Carré ou rectangle bleu',
    regle: 'Ils renseignent sans rien imposer — sauf quand ils créent un régime (autoroute, sens unique).' }
];

/* Attribution des visuels — obligatoire au titre des licences Creative Commons.
   Les fichiers sont ceux de Wikimedia Commons, non modifiés. */
const CREDITS = [
  { auteur: 'Roulex 45', licence: 'CC BY-SA 3.0 et 4.0', n: 36 },
  { auteur: 'Grondin', licence: 'CC BY-SA 3.0', n: 1 },
  { auteur: 'Gigillo83', licence: 'CC BY-SA 4.0', n: 1 },
  { auteur: 'Roulex 45', licence: 'domaine public', n: 2 }
];
