/* =========================================================
   LES PANNEAUX
   Chaque panneau est redessiné ici en SVG (repère 100×100).
   Les formes et couleurs suivent la réglementation française.
   ========================================================= */
'use strict';

/* --- les silhouettes de base --- */
const FORMES = {
  danger: i => `<polygon points="50,7 95,86 5,86" fill="#fff" stroke="#D62128" stroke-width="9" stroke-linejoin="round"/>${i}`,
  interdit: i => `<circle cx="50" cy="50" r="43" fill="#fff" stroke="#D62128" stroke-width="10"/>${i}`,
  obligation: i => `<circle cx="50" cy="50" r="46" fill="#1B4B9B"/>${i}`,
  indication: i => `<rect x="6" y="6" width="88" height="88" rx="6" fill="#1B4B9B" stroke="#fff" stroke-width="5"/>${i}`,
  cedez: i => `<polygon points="50,93 95,14 5,14" fill="#fff" stroke="#D62128" stroke-width="9" stroke-linejoin="round"/>${i}`,
  stop: i => `<polygon points="30,4 70,4 96,30 96,70 70,96 30,96 4,70 4,30" fill="#D62128" stroke="#fff" stroke-width="4"/>${i}`,
  losange: i => `<polygon points="50,5 95,50 50,95 5,50" fill="#fff" stroke="#fff" stroke-width="2"/><polygon points="50,14 86,50 50,86 14,50" fill="#F2C200"/>${i}`,
  fin: i => `<circle cx="50" cy="50" r="43" fill="#fff" stroke="#333" stroke-width="4"/>${i}`
};

/* --- quelques pictogrammes réutilisés --- */
const P = {
  voiture: (x, y, s, c) => `<g transform="translate(${x},${y}) scale(${s})" fill="${c}">
    <path d="M-20 4 L-16 -6 Q-15 -9 -12 -9 L12 -9 Q15 -9 16 -6 L20 4 L20 9 Q20 11 18 11 L15 11 Q13 11 13 9 L-13 9 Q-13 11 -15 11 L-18 11 Q-20 11 -20 9 Z"/>
    <rect x="-11" y="-7" width="22" height="7" rx="2" fill="#fff" opacity=".55"/></g>`,
  pieton: (x, y, s, c) => `<g transform="translate(${x},${y}) scale(${s})" fill="${c}">
    <circle cx="0" cy="-16" r="4.4"/>
    <path d="M-1.5 -11 L1.5 -11 L5 -2 L3 -1 L1 -5 L1.5 3 L6 13 L3.5 14.5 L-1 5 L-4.5 14.5 L-7 13 L-3 3 L-3 -5 L-5.5 -1 L-7.5 -2 Z"/></g>`,
  fleche: (a, c) => `<g transform="rotate(${a} 50 50)"><path d="M50 22 L64 46 L56 46 L56 76 L44 76 L44 46 L36 46 Z" fill="${c}"/></g>`
};

/* --- la liste --- */
const PANNEAUX = [
  /* ================= DANGER ================= */
  { id: 'virage-d', cat: 'danger', nom: 'Virage à droite',
    svg: FORMES.danger(`<path d="M42 76 L42 56 Q42 38 58 38 L58 30" stroke="#111" stroke-width="7" fill="none"/><path d="M58 24 L64 36 L52 36 Z" fill="#111"/>`),
    quoi: 'Un virage dangereux vers la droite.',
    faire: 'Ralentir avant le virage, se tenir à droite et ne pas doubler.' },
  { id: 'virages', cat: 'danger', nom: 'Succession de virages',
    svg: FORMES.danger(`<path d="M42 78 Q42 62 56 58 Q68 54 68 40 L68 32" stroke="#111" stroke-width="7" fill="none"/><path d="M68 24 L74 36 L62 36 Z" fill="#111"/>`),
    quoi: 'Plusieurs virages rapprochés, le premier vers la droite.',
    faire: 'Adapter son allure sur toute la section, dépassement très risqué.' },
  { id: 'cassis', cat: 'danger', nom: 'Cassis ou dos-d\'âne',
    svg: FORMES.danger(`<path d="M22 70 Q34 46 46 70" stroke="#111" stroke-width="7" fill="none"/><path d="M54 70 Q66 46 78 70" stroke="#111" stroke-width="7" fill="none"/>`),
    quoi: 'La chaussée présente une bosse ou un creux marqué.',
    faire: 'Ralentir franchement : la visibilité et la tenue de route sont réduites.' },
  { id: 'retreci', cat: 'danger', nom: 'Chaussée rétrécie',
    svg: FORMES.danger(`<path d="M30 78 L38 44" stroke="#111" stroke-width="7"/><path d="M70 78 L62 44" stroke="#111" stroke-width="7"/>`),
    quoi: 'La route devient plus étroite, d\'un côté ou des deux.',
    faire: 'Ralentir et se préparer à céder le passage si l\'on ne peut pas croiser.' },
  { id: 'pietons', cat: 'danger', nom: 'Passage pour piétons',
    svg: FORMES.danger(`${P.pieton(50, 60, 1.5, '#111')}<rect x="30" y="76" width="40" height="4" fill="#111"/>`),
    quoi: 'Un passage piétons est annoncé plus loin.',
    faire: 'Ralentir et être prêt à s\'arrêter. Le piéton engagé est prioritaire.' },
  { id: 'enfants', cat: 'danger', nom: 'Endroit fréquenté par des enfants',
    svg: FORMES.danger(`${P.pieton(40, 62, 1.1, '#111')}${P.pieton(60, 64, .85, '#111')}`),
    quoi: 'École, sortie de classe, aire de jeux à proximité.',
    faire: 'Lever le pied et surveiller les trottoirs : un enfant peut surgir.' },
  { id: 'travaux', cat: 'danger', nom: 'Travaux',
    svg: FORMES.danger(`<g fill="#111"><rect x="46" y="46" width="8" height="30"/><path d="M38 44 L62 44 L58 36 L42 36 Z"/><circle cx="50" cy="32" r="5"/></g>`),
    quoi: 'Chantier sur ou au bord de la chaussée.',
    faire: 'Ralentir, respecter la signalisation temporaire, elle prime sur la permanente.' },
  { id: 'glissante', cat: 'danger', nom: 'Chaussée glissante',
    svg: FORMES.danger(`${P.voiture(50, 58, .95, '#111')}<path d="M26 74 Q34 66 30 60" stroke="#111" stroke-width="4" fill="none"/><path d="M74 74 Q66 66 70 60" stroke="#111" stroke-width="4" fill="none"/>`),
    quoi: 'Risque de glissance : pluie, verglas, gravillons, boue.',
    faire: 'Réduire la vitesse, éviter les freinages et coups de volant brusques.' },
  { id: 'feux', cat: 'danger', nom: 'Feux tricolores',
    svg: FORMES.danger(`<rect x="40" y="34" width="20" height="44" rx="5" fill="#111"/><circle cx="50" cy="44" r="5" fill="#D62128"/><circle cx="50" cy="56" r="5" fill="#F2C200"/><circle cx="50" cy="68" r="5" fill="#2E9E4F"/>`),
    quoi: 'Une signalisation lumineuse est annoncée.',
    faire: 'Anticiper : préparer son freinage, le feu peut passer au rouge.' },
  { id: 'descente', cat: 'danger', nom: 'Descente dangereuse',
    svg: FORMES.danger(`<path d="M26 44 L76 78 L26 78 Z" fill="#111"/><text x="52" y="62" font-size="20" fill="#fff" font-family="Arial" font-weight="bold">%</text>`),
    quoi: 'Forte pente descendante.',
    faire: 'Rétrograder et utiliser le frein moteur, ne pas rester sur la pédale de frein.' },
  { id: 'deux-sens', cat: 'danger', nom: 'Circulation dans les deux sens',
    svg: FORMES.danger(`<g fill="#111"><path d="M38 78 L38 44 L32 44 L41 30 L50 44 L44 44 L44 78 Z"/><path d="M62 34 L62 68 L68 68 L59 82 L50 68 L56 68 L56 34 Z"/></g>`),
    quoi: 'Fin d\'une chaussée à sens unique : on va croiser des véhicules.',
    faire: 'Serrer à droite, redoubler d\'attention avant tout dépassement.' },
  { id: 'animaux', cat: 'danger', nom: 'Traversée d\'animaux sauvages',
    svg: FORMES.danger(`<g fill="#111"><path d="M34 74 L38 58 L44 52 L58 52 L66 58 L68 74 L62 74 L60 62 L44 62 L42 74 Z"/><path d="M58 52 L62 40 M66 44 L62 40 M58 40 L62 40" stroke="#111" stroke-width="3"/></g>`),
    quoi: 'Passage fréquent de gibier.',
    faire: 'Ralentir, surtout à l\'aube et au crépuscule. Un animal est rarement seul.' },

  /* ================= INTERDICTION ================= */
  { id: 'sens-interdit', cat: 'interdiction', nom: 'Sens interdit',
    svg: `<circle cx="50" cy="50" r="43" fill="#D62128" stroke="#fff" stroke-width="5"/><rect x="22" y="43" width="56" height="14" rx="2" fill="#fff"/>`,
    quoi: 'Accès interdit à tous les véhicules dans ce sens.',
    faire: 'Ne pas s\'engager, jamais. C\'est l\'une des infractions les plus dangereuses.' },
  { id: 'stationnement-interdit', cat: 'interdiction', nom: 'Stationnement interdit',
    svg: `<circle cx="50" cy="50" r="43" fill="#1B4B9B" stroke="#D62128" stroke-width="9"/><line x1="24" y1="76" x2="76" y2="24" stroke="#D62128" stroke-width="9"/>`,
    quoi: 'Interdiction de stationner. L\'arrêt reste possible.',
    faire: 'On peut s\'arrêter pour laisser monter ou descendre, mais pas quitter son véhicule.' },
  { id: 'arret-interdit', cat: 'interdiction', nom: 'Arrêt et stationnement interdits',
    svg: `<circle cx="50" cy="50" r="43" fill="#1B4B9B" stroke="#D62128" stroke-width="9"/><line x1="24" y1="76" x2="76" y2="24" stroke="#D62128" stroke-width="9"/><line x1="24" y1="24" x2="76" y2="76" stroke="#D62128" stroke-width="9"/>`,
    quoi: 'Ni arrêt, ni stationnement.',
    faire: 'On ne s\'immobilise pas du tout, même moteur tournant.' },
  { id: 'limite-50', cat: 'interdiction', nom: 'Limitation à 50 km/h',
    svg: FORMES.interdit(`<text x="50" y="66" font-size="42" text-anchor="middle" fill="#111" font-family="Arial" font-weight="bold">50</text>`),
    quoi: 'Vitesse maximale autorisée : 50 km/h.',
    faire: 'La limite s\'applique jusqu\'au prochain panneau ou à la prochaine intersection.' },
  { id: 'depassement-interdit', cat: 'interdiction', nom: 'Dépassement interdit',
    svg: FORMES.interdit(`${P.voiture(36, 52, .7, '#111')}${P.voiture(64, 52, .7, '#D62128')}`),
    quoi: 'Interdiction de dépasser tout véhicule à moteur (sauf deux-roues).',
    faire: 'Rester dans sa file jusqu\'au panneau de fin d\'interdiction.' },
  { id: 'acces-interdit', cat: 'interdiction', nom: 'Accès interdit à tout véhicule',
    svg: FORMES.interdit(``),
    quoi: 'Circulation interdite dans les deux sens.',
    faire: 'Chercher un autre itinéraire. Souvent complété par un panonceau (« sauf riverains »).' },
  { id: 'fin-limitation', cat: 'interdiction', nom: 'Fin de toutes les interdictions',
    svg: FORMES.fin(`<line x1="26" y1="74" x2="74" y2="26" stroke="#333" stroke-width="5"/><line x1="34" y1="78" x2="78" y2="34" stroke="#333" stroke-width="5"/>`),
    quoi: 'Toutes les interdictions précédentes cessent.',
    faire: 'On revient aux règles générales de la route où l\'on se trouve.' },

  /* ================= OBLIGATION ================= */
  { id: 'tout-droit', cat: 'obligation', nom: 'Direction obligatoire : tout droit',
    svg: FORMES.obligation(P.fleche(0, '#fff')),
    quoi: 'Il faut continuer tout droit.',
    faire: 'Ni à gauche, ni à droite au prochain point.' },
  { id: 'a-droite', cat: 'obligation', nom: 'Direction obligatoire : à droite',
    svg: FORMES.obligation(P.fleche(90, '#fff')),
    quoi: 'Il faut tourner à droite.',
    faire: 'Se placer et signaler son intention à l\'avance.' },
  { id: 'contournement', cat: 'obligation', nom: 'Contournement obligatoire par la droite',
    svg: FORMES.obligation(`<path d="M32 74 Q32 34 62 34 L62 26 L80 40 L62 54 L62 46 Q44 46 44 74 Z" fill="#fff"/>`),
    quoi: 'L\'obstacle doit être contourné par la droite.',
    faire: 'Suivre la flèche : on ne passe pas de l\'autre côté.' },
  { id: 'piste-cyclable', cat: 'obligation', nom: 'Piste cyclable obligatoire',
    svg: FORMES.obligation(`<g stroke="#fff" stroke-width="4" fill="none"><circle cx="34" cy="64" r="13"/><circle cx="68" cy="64" r="13"/><path d="M34 64 L46 44 L60 44 M46 44 L68 64"/></g><circle cx="60" cy="36" r="5" fill="#fff"/>`),
    quoi: 'Piste réservée aux cyclistes, qui doivent l\'emprunter.',
    faire: 'En voiture : ne jamais y circuler ni s\'y arrêter.' },
  { id: 'vitesse-mini', cat: 'obligation', nom: 'Vitesse minimale obligatoire',
    svg: FORMES.obligation(`<text x="50" y="66" font-size="40" text-anchor="middle" fill="#fff" font-family="Arial" font-weight="bold">30</text>`),
    quoi: 'Il faut rouler au moins à cette vitesse.',
    faire: 'Si le véhicule ne peut pas la tenir, cette voie lui est interdite.' },

  /* ================= PRIORITÉ ================= */
  { id: 'stop', cat: 'priorite', nom: 'Stop',
    svg: FORMES.stop(`<text x="50" y="60" font-size="26" text-anchor="middle" fill="#fff" font-family="Arial" font-weight="bold">STOP</text>`),
    quoi: 'Arrêt absolu et obligatoire à la ligne.',
    faire: 'Les roues doivent s\'immobiliser complètement, même si la route est vide.' },
  { id: 'cedez', cat: 'priorite', nom: 'Cédez le passage',
    svg: FORMES.cedez(``),
    quoi: 'Laisser passer les véhicules venant sur la route abordée.',
    faire: 'On peut passer sans s\'arrêter si la voie est libre — mais on doit pouvoir s\'arrêter.' },
  { id: 'prioritaire', cat: 'priorite', nom: 'Route prioritaire',
    svg: FORMES.losange(``),
    quoi: 'On circule sur une route prioritaire.',
    faire: 'La priorité à droite ne s\'applique plus aux intersections suivantes.' },
  { id: 'fin-prioritaire', cat: 'priorite', nom: 'Fin de route prioritaire',
    svg: FORMES.losange(`<line x1="20" y1="80" x2="80" y2="20" stroke="#111" stroke-width="5"/>`),
    quoi: 'La route cesse d\'être prioritaire.',
    faire: 'On repasse aux règles habituelles : attention à la priorité à droite.' },
  { id: 'priorite-droite', cat: 'priorite', nom: 'Intersection à priorité à droite',
    svg: FORMES.danger(`<path d="M50 34 L50 80 M28 60 L72 60" stroke="#111" stroke-width="7"/>`),
    quoi: 'Carrefour où la priorité à droite s\'applique.',
    faire: 'Céder le passage à tout véhicule arrivant de sa droite.' },
  { id: 'priorite-sens-inverse', cat: 'priorite', nom: 'Priorité sur la circulation en sens inverse',
    svg: `<rect x="6" y="6" width="88" height="88" rx="6" fill="#1B4B9B" stroke="#fff" stroke-width="5"/><path d="M38 78 L38 40 L32 40 L41 24 L50 40 L44 40 L44 78 Z" fill="#fff"/><path d="M62 28 L62 62 L68 62 L59 78 L50 62 L56 62 L56 28 Z" fill="#D62128"/>`,
    quoi: 'Dans un passage étroit, on est prioritaire.',
    faire: 'On passe en premier, mais sans forcer : vérifier que l\'autre s\'arrête.' },

  /* ================= INDICATION ================= */
  { id: 'passage-pietons', cat: 'indication', nom: 'Passage pour piétons',
    svg: FORMES.indication(`${P.pieton(50, 52, 1.5, '#fff')}<g fill="#fff"><rect x="26" y="74" width="7" height="12"/><rect x="38" y="74" width="7" height="12"/><rect x="50" y="74" width="7" height="12"/><rect x="62" y="74" width="7" height="12"/></g>`),
    quoi: 'Emplacement d\'un passage piétons.',
    faire: 'Céder le passage à tout piéton engagé ou manifestant l\'intention de traverser.' },
  { id: 'stationnement', cat: 'indication', nom: 'Stationnement autorisé',
    svg: FORMES.indication(`<text x="50" y="72" font-size="60" text-anchor="middle" fill="#fff" font-family="Arial" font-weight="bold">P</text>`),
    quoi: 'Emplacement où le stationnement est permis.',
    faire: 'Lire les panonceaux : durée, jours, zone payante.' },
  { id: 'impasse', cat: 'indication', nom: 'Impasse',
    svg: FORMES.indication(`<rect x="46" y="30" width="8" height="46" fill="#fff"/><rect x="30" y="30" width="40" height="7" fill="#D62128"/>`),
    quoi: 'La voie ne débouche sur rien.',
    faire: 'Il faudra faire demi-tour : ne pas s\'y engager avec une remorque sans vérifier.' },
  { id: 'sens-unique', cat: 'indication', nom: 'Sens unique',
    svg: `<rect x="6" y="30" width="88" height="40" rx="4" fill="#1B4B9B" stroke="#fff" stroke-width="4"/><path d="M24 50 L64 50 M56 40 L68 50 L56 60" stroke="#fff" stroke-width="7" fill="none"/>`,
    quoi: 'La circulation se fait dans un seul sens, celui de la flèche.',
    faire: 'On peut utiliser toute la largeur, mais interdiction de revenir en arrière.' },
  { id: 'autoroute', cat: 'indication', nom: 'Entrée d\'autoroute',
    svg: FORMES.indication(`<path d="M22 82 L40 24 L60 24 L78 82 L64 82 L52 36 L48 36 L36 82 Z" fill="#fff"/><rect x="46" y="52" width="8" height="30" fill="#fff"/>`),
    quoi: 'Début de l\'autoroute et de ses règles particulières.',
    faire: 'Vitesse maxi 130 (110 par temps de pluie), arrêt interdit sauf urgence sur la bande.' },
  { id: 'fin-autoroute', cat: 'indication', nom: 'Fin d\'autoroute',
    svg: FORMES.indication(`<path d="M22 82 L40 24 L60 24 L78 82 L64 82 L52 36 L48 36 L36 82 Z" fill="#fff" opacity=".55"/><rect x="46" y="52" width="8" height="30" fill="#fff" opacity=".55"/><line x1="18" y1="84" x2="84" y2="18" stroke="#D62128" stroke-width="7"/>`),
    quoi: 'Les règles de l\'autoroute cessent de s\'appliquer.',
    faire: 'Ralentir : on retrouve des carrefours, des piétons, des vitesses plus basses.' }
];

const CATEGORIES = [
  { id: 'danger', nom: 'Danger', forme: 'Triangle à bord rouge',
    regle: 'Ils annoncent un risque. Placés à 150 m environ hors agglomération, 50 m en ville.' },
  { id: 'interdiction', nom: 'Interdiction', forme: 'Disque à bord rouge',
    regle: 'Ils interdisent. Valables jusqu\'au panneau de fin, à la prochaine intersection, ou selon le panonceau.' },
  { id: 'obligation', nom: 'Obligation', forme: 'Disque bleu',
    regle: 'Ils imposent un comportement. Le bleu commande, le rouge interdit.' },
  { id: 'priorite', nom: 'Priorité', forme: 'Formes propres',
    regle: 'Ils disent qui passe en premier. En l\'absence de tout panneau : priorité à droite.' },
  { id: 'indication', nom: 'Indication', forme: 'Carré ou rectangle bleu',
    regle: 'Ils renseignent, sans rien imposer — sauf quand ils créent un régime (autoroute, sens unique).' }
];
