/* =========================================================
   LES RÈGLES ET LES QUESTIONS — permis voiture
   Fiches et questions rédigées pour ce site.
   ========================================================= */
'use strict';

const FICHES = [
  {
    id: 'vitesses', titre: 'Les vitesses', emoji: '🚗',
    lignes: [
      ['En agglomération', '50 km/h', 'Dès le panneau d\'entrée de ville, sans qu\'aucun chiffre soit affiché.'],
      ['Route à double sens, sans séparateur', '80 km/h', 'Certains départements sont remontés à 90 : c\'est le panneau qui fait foi.'],
      ['Route à chaussées séparées', '110 km/h', '100 km/h par temps de pluie.'],
      ['Autoroute', '130 km/h', '110 km/h par temps de pluie.'],
      ['Visibilité inférieure à 50 m', '50 km/h', 'Brouillard, neige, pluie forte : partout, y compris sur autoroute.'],
      ['Voie de gauche sur autoroute', '80 km/h minimum', 'Par beau temps et de jour : trop lent, on gêne et on est verbalisable.']
    ],
    note: 'Permis probatoire : 110 sur autoroute, 100 sur voie rapide, 80 sur route — quel que soit le panneau.'
  },
  {
    id: 'priorites', titre: 'Qui passe en premier', emoji: '🔀',
    lignes: [
      ['Aucun panneau, aucun marquage', 'Priorité à droite', 'La règle par défaut, même pour une petite rue.'],
      ['Panneau « Cédez le passage »', 'On laisse passer', 'On peut ne pas s\'arrêter si la voie est libre.'],
      ['Panneau « Stop »', 'Arrêt absolu', 'Les roues s\'immobilisent, même sans personne en vue.'],
      ['Rond-point classique', 'Ceux qui tournent', 'Signalé par un cédez-le-passage à chaque entrée.'],
      ['Véhicule d\'urgence en action', 'Il passe', 'On se range et on s\'arrête, sans franchir un feu rouge dangereusement.'],
      ['Tramway', 'Toujours prioritaire', 'Il ne peut ni dévier ni freiner court.']
    ],
    note: 'L\'ordre à retenir : l\'agent prime sur le feu, le feu prime sur le panneau, le panneau prime sur le marquage au sol.'
  },
  {
    id: 'depassement', titre: 'Le dépassement', emoji: '↩️',
    lignes: [
      ['De quel côté', 'Par la gauche', 'Sauf véhicule qui tourne à gauche, ou circulation en files en ville.'],
      ['Écart avec un cycliste', '1 m en ville', '1,50 m hors agglomération.'],
      ['Interdit', 'Sans visibilité', 'Sommet de côte, virage, intersection, passage à niveau.'],
      ['Véhicule arrêté au passage piéton', 'Interdit de le doubler', 'Il masque forcément quelqu\'un qui traverse.'],
      ['Le rabattement', 'Sans gêner', 'On voit les deux phares du dépassé dans son rétroviseur intérieur.']
    ],
    note: 'Un dépassement se décide avant de le commencer : si vous hésitez, c\'est non. Renoncer coûte trente secondes.'
  },
  {
    id: 'stationnement', titre: 'Arrêt et stationnement', emoji: '🅿️',
    lignes: [
      ['Arrêt', 'Momentané', 'Le conducteur reste au volant ou à proximité immédiate.'],
      ['Stationnement', 'Prolongé', 'Dès qu\'on quitte le véhicule ou qu\'on s\'installe.'],
      ['Très gênant', '135 €', 'Trottoir, passage piéton, piste cyclable, place handicapé.'],
      ['Dangereux', '135 € + 3 points', 'Sommet de côte, virage sans visibilité, intersection.'],
      ['Abusif', 'Fourrière possible', 'Plus de 7 jours au même emplacement.']
    ],
    note: 'Sur trottoir, on ne se gare jamais « juste un peu » : une poussette ou un fauteuil doit pouvoir passer.'
  },
  {
    id: 'alcool', titre: 'Alcool et stupéfiants', emoji: '🚫',
    lignes: [
      ['Permis classique', '0,5 g/L de sang', 'Soit 0,25 mg/L d\'air expiré.'],
      ['Permis probatoire', '0,2 g/L de sang', 'Soit 0,10 mg/L — en pratique, aucun verre.'],
      ['À partir de 0,8 g/L', 'Délit', 'Jusqu\'à 4 500 € d\'amende, 2 ans de prison, 6 points.'],
      ['Stupéfiants', 'Tolérance zéro', 'La seule présence dans le sang constitue un délit.'],
      ['Un verre standard', '+0,20 à 0,25 g/L', 'Une bière, un ballon de vin et un whisky comptent pareil.']
    ],
    note: 'Rien ne fait baisser le taux plus vite : ni le café, ni la douche, ni le sport. Seul le temps compte, environ 0,15 g/L par heure.'
  },
  {
    id: 'distances', titre: 'Distances et freinage', emoji: '📏',
    lignes: [
      ['Distance de sécurité', '2 secondes', 'Repérez un point fixe : deux secondes doivent s\'écouler avant d\'y arriver.'],
      ['Distance d\'arrêt', 'Réaction + freinage', 'La réaction, c\'est ce qu\'on parcourt avant même de freiner.'],
      ['Temps de réaction', '1 seconde environ', 'Plus long si l\'on est fatigué, distrait ou sous influence.'],
      ['Sur route mouillée', 'Distance doublée', 'L\'adhérence chute surtout aux premières gouttes.'],
      ['Dans un tunnel', '2 s ou 150 m', 'Et 100 m si l\'on est à l\'arrêt.']
    ],
    note: 'À 90 km/h on parcourt 25 m pendant la seule seconde de réaction. Quand la vitesse double, la distance de freinage est multipliée par quatre.'
  },
  {
    id: 'meteo', titre: 'Pluie, brouillard, verglas', emoji: '🌧️',
    lignes: [
      ['Pluie sur autoroute', '110 km/h', '100 sur voie rapide. Les limites à 80 restent à 80.'],
      ['Brouillard épais', '50 km/h', 'Dès que la visibilité descend sous 50 m.'],
      ['Feux de brouillard arrière', 'Brouillard ou neige', 'Interdits sous la pluie seule : ils éblouissent ceux qui suivent.'],
      ['Aquaplaning', 'Ne pas freiner', 'Lever le pied, tenir le volant droit, attendre que ça reprenne.'],
      ['Verglas', 'Tout en douceur', 'Aucun geste brusque : ni frein, ni volant, ni accélérateur.']
    ],
    note: 'Le plus glissant, c\'est le début d\'une averse après plusieurs jours secs : l\'eau soulève les huiles déposées sur la route.'
  },
  {
    id: 'autoroute', titre: 'Autoroute et tunnels', emoji: '🛣️',
    lignes: [
      ['S\'insérer', 'Sur la bande d\'accélération', 'On accélère pour prendre la vitesse du flux : on n\'est pas prioritaire.'],
      ['Bande d\'arrêt d\'urgence', 'Urgence seulement', 'Y circuler ou s\'y reposer est verbalisé et très dangereux.'],
      ['En panne', 'Gilet avant de sortir', 'Puis derrière la glissière, jamais dans le véhicule.'],
      ['Demi-tour, marche arrière', 'Interdits', 'Même si l\'on rate sa sortie : on continue jusqu\'à la suivante.'],
      ['Tunnel', 'Feux allumés, radio', 'Écart de 150 m, 100 m à l\'arrêt. Repérer les issues de secours.']
    ],
    note: 'Une pause s\'impose toutes les deux heures. Sur un long trajet, la fatigue tue plus discrètement que la vitesse.'
  },
  {
    id: 'papiers', titre: 'Équipement et papiers', emoji: '🦺',
    lignes: [
      ['Gilet de haute visibilité', 'Dans l\'habitacle', 'À portée de main sans avoir à sortir du véhicule.'],
      ['Triangle de présignalisation', 'À bord', 'Posé à 30 m environ — jamais sur autoroute, trop dangereux.'],
      ['Pneus', '1,6 mm minimum', 'Profondeur des sculptures, sur toute la surface de roulement.'],
      ['À présenter en contrôle', 'Permis, carte grise, assurance', 'Le défaut de présentation immédiate est verbalisable.'],
      ['Enfant de moins de 10 ans', 'À l\'arrière', 'Dans un dispositif homologué adapté à sa taille et à son poids.']
    ],
    note: 'Sur l\'airbag passager : jamais de siège dos à la route devant un airbag actif.'
  },
  {
    id: 'permis', titre: 'Le permis à points', emoji: '🪪',
    lignes: [
      ['Permis probatoire', '6 points', '3 ans, ou 2 ans après une conduite accompagnée.'],
      ['Permis définitif', '12 points', 'Atteints progressivement si aucune infraction.'],
      ['Téléphone tenu en main', '3 points + 135 €', 'Même à l\'arrêt à un feu, moteur tournant.'],
      ['Ceinture non attachée', '3 points + 135 €', 'Pour le conducteur, et pour chaque passager majeur.'],
      ['Feu rouge grillé', '4 points + 135 €', 'Le feu orange impose déjà l\'arrêt si l\'on peut le faire sans danger.'],
      ['Refus de priorité', '4 points + 135 €', 'L\'une des premières causes d\'accident en intersection.']
    ],
    note: 'Solde à zéro : le permis est invalidé. On repasse le code après un délai, et conduire entre-temps est un délit.'
  },
  {
    id: 'accident', titre: 'En cas d\'accident', emoji: '🚑',
    lignes: [
      ['1. Protéger', 'Sécuriser les lieux', 'Warnings, gilet, se garer plus loin, éloigner les témoins de la chaussée.'],
      ['2. Alerter', '112', 'Numéro européen. 15 SAMU, 18 pompiers, 17 police.'],
      ['3. Secourir', 'Sans aggraver', 'On ne déplace une victime que s\'il y a un danger immédiat.'],
      ['Casque d\'un motard', 'Ne pas le retirer', 'Sauf si la victime ne respire pas, et à deux personnes.'],
      ['Constat amiable', 'À remplir sur place', 'Les croquis et les cases cochées comptent plus que les commentaires.']
    ],
    note: 'Ne jamais donner à boire à une victime, et couvrir pour éviter qu\'elle se refroidisse.'
  },
  {
    id: 'ville', titre: 'Conduire en ville', emoji: '🏙️',
    lignes: [
      ['Zone 30', '30 km/h', 'Les piétons peuvent traverser partout, pas seulement aux passages.'],
      ['Zone de rencontre', '20 km/h', 'Le piéton est prioritaire sur toute la largeur de la rue.'],
      ['Zone piétonne', 'Circulation interdite', 'Sauf autorisation, et au pas.'],
      ['Sas vélo', 'Interdit aux voitures', 'L\'espace devant la ligne au feu est réservé aux cyclistes.'],
      ['Bus qui redémarre', 'Lui céder le passage', 'En agglomération, c\'est une obligation.']
    ],
    note: 'En ville, l\'angle mort tue : un cycliste ou un piéton peut disparaître complètement du champ des rétroviseurs.'
  }
];

/* --- les questions : une seule bonne réponse par question --- */
const QUESTIONS = [
  { q: 'Vous abordez une intersection sans aucun panneau ni marquage. Un véhicule arrive à votre droite.',
    r: ['Vous lui cédez le passage', 'Vous passez, vous êtes déjà engagé', 'Le plus rapide passe', 'Vous klaxonnez et vous passez'], b: 0,
    e: 'Sans indication contraire, la priorité à droite s\'applique. C\'est la règle par défaut en France.' },
  { q: 'Un panneau triangulaire à bord rouge annonce quelque chose. Que fait-il ?',
    r: ['Il interdit', 'Il prévient d\'un danger', 'Il oblige', 'Il informe seulement'], b: 1,
    e: 'Le triangle rouge annonce toujours un danger. Le disque rouge interdit, le disque bleu oblige.' },
  { q: 'Sur autoroute, il pleut. Votre vitesse maximale est de :',
    r: ['130 km/h', '110 km/h', '100 km/h', '90 km/h'], b: 1,
    e: 'Par temps de pluie : 110 sur autoroute, 100 sur voie rapide.' },
  { q: 'Vous avez le permis depuis un an. Sur autoroute, vous ne devez pas dépasser :',
    r: ['130 km/h', '120 km/h', '110 km/h', '100 km/h'], b: 2,
    e: 'Pendant le permis probatoire : 110 sur autoroute, 100 sur voie rapide, 80 sur route.' },
  { q: 'Le taux d\'alcool maximal pour un conducteur en permis probatoire est de :',
    r: ['0,5 g/L de sang', '0,2 g/L de sang', '0,8 g/L de sang', 'Aucune limite précise'], b: 1,
    e: '0,2 g/L, soit 0,10 mg/L d\'air expiré. En pratique : pas un verre.' },
  { q: 'Le feu passe à l\'orange alors que vous en êtes tout près, à bonne vitesse.',
    r: ['Vous accélérez pour passer', 'Vous freinez brutalement', 'Vous passez si l\'arrêt ne peut se faire sans danger', 'Vous vous arrêtez au milieu du carrefour'], b: 2,
    e: 'L\'orange impose l\'arrêt, sauf si celui-ci ne peut être fait dans des conditions de sécurité suffisantes.' },
  { q: 'Un panneau « Stop » vous fait face et la route est parfaitement dégagée.',
    r: ['Vous ralentissez fortement puis passez', 'Vous marquez l\'arrêt complet', 'Vous passez sans ralentir', 'Vous cédez seulement à droite'], b: 1,
    e: 'Le Stop impose un arrêt absolu : les roues doivent s\'immobiliser, même si personne n\'arrive.' },
  { q: 'La distance de sécurité minimale avec le véhicule qui précède correspond à :',
    r: ['1 seconde', '2 secondes', '5 mètres', 'La longueur d\'une voiture'], b: 1,
    e: 'Deux secondes. Repérez un point fixe : deux secondes doivent s\'écouler avant que vous y arriviez.' },
  { q: 'Un disque bleu avec une flèche blanche vers la droite signifie :',
    r: ['Direction conseillée', 'Direction obligatoire à droite', 'Interdiction d\'aller à droite', 'Route prioritaire à droite'], b: 1,
    e: 'Le bleu commande. Ici, on doit tourner à droite.' },
  { q: 'Un panneau rond bleu barré d\'une seule diagonale rouge signifie :',
    r: ['Arrêt et stationnement interdits', 'Stationnement interdit', 'Sens interdit', 'Fin de stationnement'], b: 1,
    e: 'Une diagonale : stationnement interdit, l\'arrêt reste possible. Deux diagonales : arrêt interdit aussi.' },
  { q: 'Le losange jaune bordé de blanc indique :',
    r: ['Une route prioritaire', 'Un danger', 'Une zone de travaux', 'Une aire de repos'], b: 0,
    e: 'Route prioritaire : la priorité à droite ne s\'applique plus aux intersections suivantes.' },
  { q: 'Votre véhicule tombe en panne sur la bande d\'arrêt d\'urgence. Vous :',
    r: ['Sortez puis enfilez le gilet', 'Enfilez le gilet avant de sortir', 'Restez au volant', 'Posez le triangle sur l\'autoroute'], b: 1,
    e: 'Le gilet s\'enfile dans l\'habitacle. Ensuite on sort côté opposé au trafic et on se met derrière la glissière.' },
  { q: 'La profondeur minimale des sculptures d\'un pneu est de :',
    r: ['1 mm', '1,6 mm', '2,5 mm', '3 mm'], b: 1,
    e: '1,6 mm sur toute la surface de roulement. En dessous, le pneu est considéré comme lisse.' },
  { q: 'Vous entrez sur un rond-point signalé par un « cédez le passage ».',
    r: ['Vous êtes prioritaire', 'Vous cédez à ceux qui y circulent', 'Priorité à droite', 'Vous devez vous arrêter'], b: 1,
    e: 'La quasi-totalité des ronds-points français fonctionne ainsi : ceux qui tournent déjà sont prioritaires.' },
  { q: 'Téléphone tenu en main au volant, à l\'arrêt à un feu rouge, moteur tournant :',
    r: ['C\'est autorisé, vous êtes à l\'arrêt', 'C\'est verbalisable', 'Seulement si vous téléphonez', 'Autorisé si le frein à main est mis'], b: 1,
    e: 'Le véhicule est toujours en circulation. C\'est 135 € et 3 points.' },
  { q: 'Un triangle rouge pointe vers le bas, sans dessin à l\'intérieur.',
    r: ['Stop', 'Cédez le passage', 'Danger indéterminé', 'Fin de priorité'], b: 1,
    e: 'C\'est le seul panneau triangulaire pointe en bas : cédez le passage.' },
  { q: 'La visibilité tombe sous 50 mètres à cause du brouillard, sur autoroute.',
    r: ['110 km/h', '90 km/h', '70 km/h', '50 km/h'], b: 3,
    e: '50 km/h partout, y compris sur autoroute, dès que la visibilité descend sous 50 m.' },
  { q: 'Vous doublez un cycliste hors agglomération. L\'écart latéral minimal est de :',
    r: ['50 cm', '1 mètre', '1,50 mètre', '2 mètres'], b: 2,
    e: '1,50 m hors agglomération, 1 m en ville.' },
  { q: 'Le permis probatoire compte au départ :',
    r: ['12 points', '8 points', '6 points', '4 points'], b: 2,
    e: '6 points, puis la majoration se fait sur 3 ans — ou 2 ans après une conduite accompagnée.' },
  { q: 'Un disque blanc bordé de rouge avec « 70 » au centre :',
    r: ['Vitesse conseillée', 'Vitesse minimale', 'Vitesse maximale autorisée', 'Distance jusqu\'au danger'], b: 2,
    e: 'Le bord rouge interdit : on ne dépasse pas 70. En bleu, ce serait une vitesse minimale.' },
  { q: 'À 90 km/h, pendant la seule seconde de temps de réaction, vous parcourez environ :',
    r: ['10 mètres', '25 mètres', '50 mètres', '90 mètres'], b: 1,
    e: 'Environ 25 m — avant même que la pédale de frein ne soit touchée.' },
  { q: 'Un agent règle la circulation et son geste contredit le feu vert.',
    r: ['Le feu prime', 'L\'agent prime', 'Le panneau prime', 'On choisit'], b: 1,
    e: 'L\'ordre est : agent, puis feu, puis panneau, puis marquage au sol.' },
  { q: 'Que veut dire un panneau carré bleu avec un grand « P » ?',
    r: ['Passage piétons', 'Stationnement autorisé', 'Poste de péage', 'Priorité'], b: 1,
    e: 'Stationnement autorisé. Les panonceaux précisent durée, jours et zone payante.' },
  { q: 'Sur une route à double sens sans séparateur central, la limite est en général de :',
    r: ['70 km/h', '80 km/h', '100 km/h', '110 km/h'], b: 1,
    e: '80 km/h depuis 2018. Certains départements sont remontés à 90 : le panneau fait foi.' },
  { q: 'La distance de freinage lorsque la vitesse double est :',
    r: ['Doublée', 'Triplée', 'Multipliée par quatre', 'Inchangée'], b: 2,
    e: 'Elle est multipliée par quatre. Une petite différence de vitesse change tout à l\'impact.' },
  { q: 'Un piéton attend visiblement au bord d\'un passage protégé.',
    r: ['Il doit attendre que la voie soit libre', 'Vous devez lui céder le passage', 'Seulement s\'il est déjà engagé', 'Vous klaxonnez'], b: 1,
    e: 'Il suffit que le piéton manifeste l\'intention de traverser. C\'est 135 € et 6 points.' },
  { q: 'Le panneau rond blanc bordé de noir, barré de traits obliques :',
    r: ['Interdiction de dépasser', 'Fin de toutes les interdictions', 'Fin d\'agglomération', 'Route prioritaire'], b: 1,
    e: 'Toutes les interdictions précédemment signalées cessent de s\'appliquer.' },
  { q: 'Vous conduisez fatigué sur un long trajet. La bonne conduite est :',
    r: ['Boire un café et continuer', 'Ouvrir la fenêtre', 'S\'arrêter et dormir 15 à 20 minutes', 'Monter le son'], b: 2,
    e: 'Seul le sommeil récupère. Une pause toutes les deux heures est la règle.' },
  { q: 'Le taux d\'alcool à partir duquel l\'infraction devient un délit est de :',
    r: ['0,5 g/L', '0,8 g/L', '1,2 g/L', '2 g/L'], b: 1,
    e: 'À partir de 0,8 g/L de sang : jusqu\'à 4 500 € d\'amende et 2 ans de prison.' },
  { q: 'Un triangle rouge avec deux enfants dessinés signifie :',
    r: ['École obligatoire', 'Endroit fréquenté par des enfants', 'Interdit aux enfants', 'Aire de jeux'], b: 1,
    e: 'C\'est un danger : sortie d\'école, aire de jeux. On lève le pied.' },
  { q: 'Sur autoroute, la bande d\'arrêt d\'urgence sert à :',
    r: ['Doubler par la droite', 'S\'arrêter en cas d\'urgence seulement', 'Se reposer', 'Téléphoner'], b: 1,
    e: 'Uniquement l\'urgence. S\'y arrêter sans motif est verbalisé.' },
  { q: 'Un panneau bleu rectangulaire avec une flèche blanche horizontale :',
    r: ['Sens unique', 'Direction obligatoire', 'Route prioritaire', 'Voie de détresse'], b: 0,
    e: 'Sens unique : on circule dans le sens de la flèche, interdiction de revenir en arrière.' },
  { q: 'Vous entrez en agglomération. Le panneau n\'affiche aucun chiffre. La vitesse est de :',
    r: ['Celle d\'avant, tant qu\'aucun panneau ne l\'indique', '50 km/h automatiquement', '30 km/h', '70 km/h'], b: 1,
    e: 'Le panneau d\'entrée d\'agglomération impose 50 km/h à lui seul, sans autre indication.' },
  { q: 'On dépasse normalement :',
    r: ['Par la droite', 'Par la gauche', 'Des deux côtés', 'Par le côté le plus libre'], b: 1,
    e: 'Par la gauche. Exceptions : véhicule qui tourne à gauche, ou circulation en files en ville.' },
  { q: 'Une voiture est arrêtée devant un passage piéton, sur la voie de droite.',
    r: ['Vous la doublez lentement', 'Vous ne la doublez pas', 'Vous doublez en klaxonnant', 'Vous doublez par la droite'], b: 1,
    e: 'Elle masque forcément un piéton. Dépasser un véhicule arrêté à un passage piéton est interdit.' },
  { q: 'Vous ratez votre sortie d\'autoroute.',
    r: ['Vous faites marche arrière', 'Vous continuez jusqu\'à la suivante', 'Vous faites demi-tour sur la BAU', 'Vous vous arrêtez pour réfléchir'], b: 1,
    e: 'Marche arrière et demi-tour sont interdits sur autoroute, et parmi les manœuvres les plus mortelles.' },
  { q: 'Vous vous insérez sur autoroute par la bande d\'accélération.',
    r: ['Vous êtes prioritaire', 'Vous adaptez votre vitesse au flux', 'Vous vous arrêtez au bout', 'Vous forcez le passage'], b: 1,
    e: 'On accélère pour prendre la vitesse du trafic. S\'arrêter en bout de bande est très dangereux.' },
  { q: 'Les feux de brouillard arrière peuvent être utilisés :',
    r: ['Sous la pluie', 'La nuit sur route non éclairée', 'Par brouillard ou chute de neige', 'Dès qu\'il fait sombre'], b: 2,
    e: 'Sous la pluie seule ils sont interdits : ils éblouissent ceux qui suivent.' },
  { q: 'Votre voiture se met à faire de l\'aquaplaning.',
    r: ['Vous freinez fort', 'Vous braquez pour reprendre le contrôle', 'Vous levez le pied, volant droit', 'Vous accélérez'], b: 2,
    e: 'Il faut laisser les pneus retrouver la route : lever le pied, ne pas freiner, ne pas braquer.' },
  { q: 'Un enfant de 8 ans peut voyager :',
    r: ['À l\'avant sans dispositif', 'À l\'arrière dans un dispositif homologué', 'Sur les genoux d\'un adulte', 'À l\'avant avec la ceinture'], b: 1,
    e: 'Jusqu\'à 10 ans, à l\'arrière et dans un dispositif adapté à sa taille et à son poids.' },
  { q: 'La zone de rencontre est limitée à :',
    r: ['30 km/h', '20 km/h', '10 km/h', '50 km/h'], b: 1,
    e: '20 km/h, et le piéton y est prioritaire sur toute la largeur de la chaussée.' },
  { q: 'Vous croisez un véhicule en montagne : vous montez, il descend, la route est étroite.',
    r: ['Vous cédez le passage', 'Il vous cède le passage', 'Le plus gros passe', 'On se débrouille'], b: 1,
    e: 'Celui qui descend cède : il lui est plus facile de repartir et de reculer que pour celui qui monte.' },
  { q: 'Le numéro d\'urgence européen est le :',
    r: ['15', '17', '18', '112'], b: 3,
    e: 'Le 112 fonctionne partout en Europe. En France : 15 SAMU, 17 police, 18 pompiers.' },
  { q: 'Sur un accident, la première chose à faire est de :',
    r: ['Secourir les victimes', 'Alerter les secours', 'Protéger les lieux', 'Prendre des photos'], b: 2,
    e: 'Protéger, Alerter, Secourir — dans cet ordre. Un suraccident ferait bien plus de victimes.' },
  { q: 'Un motard est au sol, casque sur la tête, il respire.',
    r: ['Vous retirez le casque', 'Vous laissez le casque en place', 'Vous l\'asseyez', 'Vous lui donnez à boire'], b: 1,
    e: 'On ne retire le casque que si la victime ne respire pas, et à deux personnes.' },
  { q: 'Le triangle de présignalisation se pose :',
    r: ['Sur la bande d\'arrêt d\'urgence', 'À 30 m environ, hors autoroute', 'Juste derrière la voiture', 'Sur le toit'], b: 1,
    e: 'Environ 30 m en amont. Sur autoroute on ne le pose pas : trop dangereux d\'y marcher.' },
  { q: 'Vous voulez vous garer et il reste une place devant une bouche d\'incendie.',
    r: ['C\'est autorisé si c\'est court', 'C\'est un stationnement gênant', 'Autorisé la nuit', 'Autorisé si vous restez dedans'], b: 1,
    e: 'C\'est gênant et verbalisé : les pompiers doivent y accéder à tout moment.' },
  { q: 'Un panneau rond bleu avec un vélo blanc signifie :',
    r: ['Vélos interdits', 'Piste cyclable obligatoire', 'Attention cyclistes', 'Piste conseillée'], b: 1,
    e: 'Rond bleu = obligation : les cyclistes doivent emprunter cette piste. En voiture, on n\'y va jamais.' },
  { q: 'Le stationnement est considéré comme abusif au-delà de :',
    r: ['24 heures', '3 jours', '7 jours', '30 jours'], b: 2,
    e: 'Plus de 7 jours au même emplacement : mise en fourrière possible.' },
  { q: 'Dans un tunnel, la distance à respecter avec le véhicule qui précède est de :',
    r: ['50 m', '100 m', '150 m', '200 m'], b: 2,
    e: '150 m en roulant, 100 m à l\'arrêt — et on allume ses feux avant d\'entrer.' },
  { q: 'Un panneau triangulaire avec une locomotive dessinée :',
    r: ['Gare à proximité', 'Passage à niveau sans barrières', 'Passage à niveau avec barrières', 'Voie ferrée parallèle'], b: 1,
    e: 'Sans barrières : c\'est le plus dangereux. On ralentit fortement et on regarde des deux côtés.' },
  { q: 'Vous arrivez à un passage à niveau, les barrières commencent à descendre.',
    r: ['Vous accélérez pour passer', 'Vous vous arrêtez', 'Vous zigzaguez entre les barrières', 'Vous klaxonnez'], b: 1,
    e: 'On s\'arrête. Un train ne peut pas freiner : il lui faut parfois un kilomètre.' },
  { q: 'Un panneau carré bleu avec un piéton sur des bandes blanches :',
    r: ['Passage piétons interdit', 'Emplacement d\'un passage piétons', 'Zone piétonne', 'Attention piétons'], b: 1,
    e: 'C\'est une indication : le passage se trouve ici. Le triangle, lui, l\'annonce plus loin.' },
  { q: 'Le panneau « chaussée glissante » représente :',
    r: ['Une voiture avec des traces de dérapage', 'Un flocon', 'Une flaque', 'Une route ondulée'], b: 0,
    e: 'Une voiture vue de derrière avec deux traces sinueuses. Pluie, verglas, gravillons, boue.' },
  { q: 'Un panneau rond rouge avec deux voitures, dont une rouge :',
    r: ['Dépassement interdit', 'Croisement difficile', 'Circulation à double sens', 'Interdit aux voitures'], b: 0,
    e: 'La voiture rouge est celle qui double : le dépassement est interdit jusqu\'au panneau de fin.' },
  { q: 'La conduite accompagnée permet de réduire le permis probatoire à :',
    r: ['1 an', '2 ans', '2 ans et demi', '3 ans'], b: 1,
    e: '2 ans au lieu de 3, avec une progression des points plus rapide.' },
  { q: 'Vous devez vous arrêter sur autoroute pour une urgence. Vous vous placez :',
    r: ['Sur la voie de droite', 'Sur la bande d\'arrêt d\'urgence, le plus à droite possible', 'Sur la bande centrale', 'N\'importe où'], b: 1,
    e: 'Le plus à droite possible, warnings allumés, puis tout le monde sort côté droit et va derrière la glissière.' },
  { q: 'Un panneau jaune en losange indique généralement :',
    r: 'x'.split('|'), b: 0, ignore: true, e: '' },
  { q: 'Le panneau de fin d\'agglomération porte :',
    r: ['Le nom de la ville barré', 'Une croix rouge', 'Le chiffre 50 barré', 'Rien du tout'], b: 0,
    e: 'Le nom barré d\'un trait rouge. La limite des 50 km/h cesse à ce panneau.' },
  { q: 'Sur autoroute, la vitesse minimale sur la voie de gauche est de :',
    r: ['Il n\'y en a pas', '60 km/h', '80 km/h', '110 km/h'], b: 2,
    e: '80 km/h par beau temps et de jour, si la voie est dégagée : plus lent, on gêne.' },
  { q: 'Le panonceau sous un panneau sert à :',
    r: ['Décorer', 'Préciser ou limiter la portée du panneau', 'Indiquer le fabricant', 'Rien d\'obligatoire'], b: 1,
    e: 'Il change souvent tout : distance, catégorie de véhicules, horaires, « sauf riverains ».' },
  { q: 'Un panneau rond bleu avec « 3,5 m » :',
    r: ['Hauteur limitée', 'Largeur limitée', 'Distance à respecter', 'Hauteur minimale'], b: 0,
    e: 'Attention : ce type de limitation est en rond ROUGE. Pensez aux barres de toit et aux vélos sur le toit.' },
  { q: 'Vous roulez de nuit et un véhicule arrive en face avec ses pleins phares.',
    r: ['Vous mettez vos pleins phares aussi', 'Vous fixez ses phares', 'Vous regardez le bord droit de la chaussée', 'Vous freinez brusquement'], b: 2,
    e: 'On se guide sur la ligne blanche de droite, pour ne pas être ébloui de face.' },
  { q: 'Les warnings (feux de détresse) s\'utilisent :',
    r: ['Pour se garer en double file', 'Pour signaler un danger ou un ralentissement brutal', 'Pour remercier', 'Sous la pluie'], b: 1,
    e: 'Ils signalent un danger. Les utiliser pour se garer en double file n\'autorise rien du tout.' },
  { q: 'Le sas vélo, au feu, est :',
    r: ['Une place de stationnement', 'Réservé aux cyclistes', 'Une zone de dépassement', 'Réservé aux motos'], b: 1,
    e: 'La voiture s\'arrête avant la première ligne. S\'y arrêter est verbalisable.' },
  { q: 'Un bus quitte son arrêt en agglomération, clignotant mis.',
    r: ['Vous passez, vous êtes prioritaire', 'Vous lui cédez le passage', 'Vous klaxonnez', 'Vous accélérez'], b: 1,
    e: 'En agglomération, il faut lui céder le passage — en ralentissant, voire en s\'arrêtant.' },
  { q: 'La distance d\'arrêt est composée de :',
    r: ['La distance de freinage seulement', 'La distance de réaction + la distance de freinage', 'La distance de sécurité', 'La distance de visibilité'], b: 1,
    e: 'On roule pendant environ une seconde avant même de commencer à freiner.' },
  { q: 'Le panneau triangulaire avec un point d\'exclamation signifie :',
    r: ['Danger prioritaire', 'Autres dangers', 'Interdiction', 'Fin de danger'], b: 1,
    e: 'Un danger sans panneau propre : c\'est le panonceau en dessous qui précise lequel.' },
  { q: 'Vous transportez un chien non attaché dans l\'habitacle.',
    r: ['C\'est sans conséquence', 'Il peut être considéré comme un objet dangereux en cas de choc', 'C\'est interdit dans tous les cas', 'Il faut le mettre à l\'avant'], b: 1,
    e: 'À 50 km/h, un chien de 20 kg pèse près d\'une tonne au moment du choc. Il doit être attaché ou en caisse.' },
  { q: 'Un panneau carré bleu avec un lit ou une tente indique :',
    r: ['Une interdiction de dormir', 'Un service ou un équipement', 'Une aire de danger', 'Une zone privée'], b: 1,
    e: 'Les panneaux carrés bleus indiquent des services : aire de repos, hôtel, essence, hôpital.' },
  { q: 'Vous êtes en permis probatoire et vous perdez 3 points d\'un coup.',
    r: ['Rien ne change', 'Vous devez suivre un stage obligatoire', 'Vous perdez le permis', 'Vous repassez le code'], b: 1,
    e: 'En probatoire, une perte de 3 points ou plus impose un stage de sensibilisation, à vos frais.' },
  { q: 'Le panneau de danger est implanté hors agglomération à environ :',
    r: ['50 m du danger', '150 m du danger', '300 m du danger', '1 km du danger'], b: 1,
    e: '150 m environ hors agglomération, 50 m en ville — sauf indication d\'un panonceau.' },
  { q: 'La ligne continue au sol :',
    r: ['Peut être franchie pour doubler un vélo', 'Ne peut jamais être franchie', 'Peut être franchie la nuit', 'Sert de décoration'], b: 0,
    e: 'Le franchissement est toléré pour dépasser un cycliste, si la visibilité le permet et sans danger.' },
  { q: 'Vous voyez un panneau rond rouge avec un vélo barré :',
    r: ['Piste cyclable', 'Accès interdit aux cycles', 'Attention cyclistes', 'Fin de piste cyclable'], b: 1,
    e: 'Rond rouge = interdiction. Les vélos ne peuvent pas emprunter cette voie.' },
  { q: 'La ceinture de sécurité est obligatoire :',
    r: ['À l\'avant seulement', 'À l\'avant et à l\'arrière', 'Hors agglomération seulement', 'Au-delà de 50 km/h'], b: 1,
    e: 'Partout, à toutes les places. C\'est 135 € et 3 points par personne non attachée.' },
  { q: 'Un véhicule d\'urgence arrive derrière vous, sirène allumée, alors que vous êtes au feu rouge.',
    r: ['Vous grillez le feu pour dégager', 'Vous vous rangez si possible, sans franchir dangereusement', 'Vous ne bougez pas', 'Vous accélérez'], b: 1,
    e: 'On facilite son passage en se serrant, mais on ne crée pas un accident en franchissant le feu.' },
  { q: 'Vous circulez sur une route à 80. Il pleut. Votre vitesse maximale est de :',
    r: ['70 km/h', '80 km/h', '90 km/h', '60 km/h'], b: 1,
    e: 'Les limites à 80 restent à 80 sous la pluie. Ce sont les 110 et 130 qui baissent.' },
  { q: 'Le panneau « chute de pierres » impose surtout de :',
    r: ['Klaxonner', 'Regarder aussi le sol de la chaussée', 'Accélérer pour passer vite', 'Rouler au milieu'], b: 1,
    e: 'Une pierre peut être tombée avant votre passage, notamment en sortie de virage.' },
  { q: 'Vous êtes ébloui par le soleil bas et ne voyez plus rien pendant un instant.',
    r: ['Vous continuez à la même vitesse', 'Vous ralentissez immédiatement', 'Vous fermez les yeux', 'Vous accélérez'], b: 1,
    e: 'On ralentit : rouler sans voir, c\'est rouler à l\'aveugle. Le pare-soleil et des lunettes aident.' },
  { q: 'Le panneau rond bleu avec un chiffre blanc, sans bord rouge, indique :',
    r: ['Une vitesse maximale', 'Une vitesse minimale obligatoire', 'Une distance', 'Un poids'], b: 1,
    e: 'Le bleu commande : il faut rouler au moins à cette vitesse.' },
  { q: 'Un panneau triangulaire à fond jaune est :',
    r: ['Un panneau permanent', 'Un panneau de signalisation temporaire', 'Un panneau touristique', 'Un panneau publicitaire'], b: 1,
    e: 'Le fond jaune signale du provisoire, et il prime sur la signalisation permanente.' },
  { q: 'Sur une route de montagne, un panneau annonce une descente à 10 %.',
    r: ['Vous mettez au point mort', 'Vous rétrogradez et utilisez le frein moteur', 'Vous freinez en continu', 'Vous coupez le moteur'], b: 1,
    e: 'Le frein moteur évite la surchauffe des freins. Le point mort en descente est interdit et dangereux.' },
  { q: 'Le taux d\'alcool baisse environ de :',
    r: ['0,05 g/L par heure', '0,15 g/L par heure', '0,5 g/L par heure', '1 g/L par heure'], b: 1,
    e: 'Environ 0,15 g/L par heure. Rien ne l\'accélère : ni café, ni douche, ni sport.' },
  { q: 'Vous voyez un panneau bleu carré avec une voiture blanche :',
    r: ['Parking', 'Route à accès réglementé', 'Autoroute', 'Voie réservée'], b: 1,
    e: 'Voie réservée aux véhicules à moteur : ni piétons, ni cyclistes, ni engins lents.' },
  { q: 'Un cycliste circule sur la chaussée alors qu\'une piste cyclable existe à côté.',
    r: ['Il est en infraction dans tous les cas', 'Cela dépend du panneau : rond bleu obligatoire, carré bleu conseillé', 'Vous devez klaxonner', 'Vous pouvez le serrer'], b: 1,
    e: 'Le rond bleu rend la piste obligatoire ; le carré bleu la rend seulement conseillée.' },
  { q: 'Le gilet de sécurité doit se trouver :',
    r: ['Dans le coffre', 'Dans l\'habitacle, à portée de main', 'Sous le capot', 'Peu importe'], b: 1,
    e: 'Il faut pouvoir l\'enfiler sans sortir du véhicule.' },
  { q: 'Un panneau annonce « chaussée rétrécie par la droite ». Vous :',
    r: ['Accélérez pour passer devant', 'Anticipez le rabattement des véhicules de droite', 'Vous déportez à gauche', 'Klaxonnez'], b: 1,
    e: 'Le rabattement se fait en fermeture éclair, chacun son tour, sans accélérer pour gagner une place.' },
  { q: 'Le stationnement sur un emplacement réservé aux personnes handicapées coûte :',
    r: ['35 €', '68 €', '135 €', '750 €'], b: 2,
    e: '135 €, et la mise en fourrière est possible. C\'est un stationnement très gênant.' },
  { q: 'La nuit, hors agglomération, sur route dégagée, vous utilisez :',
    r: ['Les feux de position', 'Les feux de croisement', 'Les feux de route', 'Les feux de brouillard'], b: 2,
    e: 'Les feux de route (pleins phares), à condition de les baisser dès qu\'un véhicule apparaît.' },
  { q: 'Un panneau rond avec deux flèches, une rouge et une noire :',
    r: ['Sens unique', 'Priorité par rapport au sens inverse ou cédez le passage', 'Interdiction de doubler', 'Route à double sens'], b: 1,
    e: 'La flèche rouge indique qui doit céder. Rond rouge : vous cédez. Carré bleu : vous êtes prioritaire.' },
  { q: 'Une zone 30 signifie que les piétons :',
    r: ['Ne traversent qu\'aux passages', 'Peuvent traverser partout', 'Sont interdits', 'Sont prioritaires partout comme en zone de rencontre'], b: 1,
    e: 'En zone 30, la traversée est autorisée partout — mais le piéton n\'est pas prioritaire pour autant.' },
  { q: 'Le contrôle technique d\'une voiture particulière se fait :',
    r: ['Tous les ans', 'Tous les 2 ans après 4 ans', 'Tous les 5 ans', 'Une seule fois'], b: 1,
    e: 'Premier contrôle dans les 6 mois avant les 4 ans du véhicule, puis tous les 2 ans.' },
  { q: 'Vous devez tourner à gauche en ville et un piéton traverse la rue où vous vous engagez.',
    r: ['Vous passez avant lui', 'Vous lui cédez le passage', 'Vous klaxonnez', 'Vous accélérez'], b: 1,
    e: 'Le piéton qui traverse la chaussée sur laquelle vous vous engagez est prioritaire.' },
  { q: 'Un panneau carré bleu avec un « P » et le mot « Ticket » :',
    r: ['Parking gratuit', 'Stationnement payant', 'Parking réservé', 'Parking souterrain'], b: 1,
    e: 'Le ticket doit rester visible derrière le pare-brise, sinon c\'est verbalisé même si vous avez payé.' },
  { q: 'La priorité à droite s\'applique aussi :',
    r: ['Sur autoroute', 'Dans un rond-point avec cédez-le-passage', 'À une intersection non signalée en ville', 'En sortie de parking privé'], b: 2,
    e: 'C\'est la règle par défaut à toute intersection non signalée, y compris avec une petite rue.' },
  { q: 'Vous êtes témoin d\'un accident. Vous vous garez :',
    r: ['Juste à côté', 'Avant l\'accident, sur le bas-côté', 'Après l\'accident, hors de la chaussée', 'En travers pour bloquer'], b: 2,
    e: 'Après l\'accident et hors de la chaussée, pour ne pas gêner les secours ni créer un suraccident.' },
  { q: 'Le panneau triangulaire avec un tramway :',
    r: ['Arrêt de tramway', 'Traversée de voies de tramway', 'Interdit aux tramways', 'Voie réservée'], b: 1,
    e: 'Le tramway est toujours prioritaire : il ne peut ni dévier, ni freiner court.' },
  { q: 'Vous circulez à 130 sur autoroute et il commence à pleuvoir légèrement.',
    r: ['Vous gardez 130', 'Vous descendez à 110', 'Vous descendez à 90', 'Vous vous arrêtez'], b: 1,
    e: '110 dès qu\'il pleut, quelle que soit l\'intensité de la pluie.' },
  { q: 'Un panneau « vent latéral » (manche à air) impose surtout :',
    r: ['De fermer les fenêtres', 'De tenir le volant fermement et de ralentir', 'D\'accélérer', 'De klaxonner'], b: 1,
    e: 'Et d\'être très vigilant en doublant un camion : on sort brutalement de son abri.' },
  { q: 'La conduite sous stupéfiants est sanctionnée :',
    r: ['Seulement si le conducteur est visiblement sous influence', 'Dès que la substance est détectée dans le sang', 'Au-delà d\'un certain seuil', 'Seulement en cas d\'accident'], b: 1,
    e: 'La simple présence suffit : c\'est un délit, indépendamment de la quantité.' }
];

/* on retire la question laissée incomplète pendant la rédaction */
for (let i = QUESTIONS.length - 1; i >= 0; i--) if (QUESTIONS[i].ignore) QUESTIONS.splice(i, 1);
