/* =========================================================
   LE PETIT CIRQUE — les banques de questions
   Toutes inédites : aucune reprise de /duo/.
   ========================================================= */

/* --- « Qui de nous deux ? » : chacun désigne un nom, on marque si
       les deux ont désigné la même personne --- */
const QUI = [
  'Qui de nous deux relit ses messages trois fois avant de les envoyer ?',
  'Qui craquerait le premier devant un chiot dans la rue ?',
  'Qui accepte un plan qui ne lui plaît pas juste pour faire plaisir ?',
  'Qui remarque en premier quand l\'autre ne va pas bien ?',
  'Qui garde le plus longtemps une chanson dans la tête ?',
  'Qui dirait « c\'est bon je suis presque prêt » en n\'ayant rien commencé ?',
  'Qui se perdrait dans une ville qu\'il connaît déjà ?',
  'Qui commande toujours la même chose au restaurant ?',
  'Qui parle le plus aux animaux ?',
  'Qui a le plus de photos floues dans sa galerie ?',
  'Qui abandonnerait une série au bout de deux épisodes ?',
  'Qui râle le plus quand il a faim ?',
  'Qui serait le plus insupportable en voiture sur un long trajet ?',
  'Qui dit « encore cinq minutes » le matin ?',
  'Qui offrirait un cadeau une semaine trop tôt parce qu\'il tient plus le secret ?',
  'Qui prend le plus soin des autres sans le dire ?',
  'Qui rirait le plus fort dans un endroit où il faut se taire ?',
  'Qui a la playlist la plus honteuse ?',
  'Qui répond le plus vite aux messages ?',
  'Qui est le plus nul aux jeux de rapidité ?',
  'Qui ferait le plus de fautes dans une dictée ?',
  'Qui garderait un ticket de cinéma pendant des années ?',
  'Qui s\'endort le premier devant un film ?',
  'Qui est le plus rancunier pour les toutes petites choses ?',
  'Qui aurait le plus peur dans une maison hantée ?',
  'Qui oserait chanter en karaoké devant tout le monde ?',
  'Qui est le plus doué pour retrouver un objet perdu ?',
  'Qui a le plus de mal à choisir un film ?',
  'Qui ferait le meilleur clown de cirque ?',
  'Qui tiendrait le plus longtemps sur un fil, pour de vrai ?',
  'Qui serait le plus stressé le jour d\'un départ en voyage ?',
  'Qui pleure le plus facilement, même pour une pub ?',
  'Qui a le plus de mal à s\'excuser en premier ?',
  'Qui s\'inquiète le plus pour l\'autre ?',
  'Qui a la plus mauvaise mémoire des dates ?',
  'Qui préparerait le meilleur petit-déjeuner surprise ?',
  'Qui parle le plus en dormant ?',
  'Qui est le plus jaloux d\'un chien ?',
  'Qui dépenserait tout d\'un coup au lieu d\'économiser ?',
  'Qui est le plus maniaque du rangement ?',
  'Qui a le plus de mal à rester assis sans rien faire ?',
  'Qui envoie le plus de vocaux de plus de trois minutes ?',
  'Qui ferait demi-tour pour un chat au bord de la route ?',
  'Qui gagnerait un concours de grimaces ?',
  'Qui se plaint le plus du froid ?',
  'Qui aurait le plus de mal à vivre sans téléphone une semaine ?',
  'Qui ment le plus mal ?',
  'Qui est le plus curieux de savoir ce qu\'il y a dans un paquet fermé ?',
  'Qui aurait le plus peur de sauter en parachute ?',
  'Qui raconte deux fois la même histoire sans s\'en rendre compte ?',
  'Qui est le plus tactile des deux ?',
  'Qui a le plus de mal à se concentrer quand l\'autre est là ?',
  'Qui se réveillerait de bonne humeur même à 6 h ?',
  'Qui a le plus besoin de silence pour réfléchir ?',
  'Qui garde le plus de choses « au cas où » ?',
  'Qui aurait le plus de mal à garder un poisson rouge en vie ?',
  'Qui prend le plus de temps sous la douche ?',
  'Qui remarque le premier quand l\'autre a changé quelque chose ?',
  'Qui serait le meilleur pour organiser une surprise ?',
  'Qui est le plus tête de mule ?',
  'Qui a le plus de mal à recevoir un compliment ?',
  'Qui dirait « je te l\'avais dit » en premier ?',
  'Qui parle le plus avec les mains ?',
  'Qui aurait le plus de mal à faire un régime ?',
  'Qui se souvient le mieux de notre première conversation ?',
  'Qui compte le plus les jours avant qu\'on se revoie ?',
  'Qui a le plus peur des insectes ?',
  'Qui ferait le plus de bruit en essayant d\'être discret ?',
  'Qui est le plus doué pour consoler quelqu\'un ?',
  'Qui aurait le plus de mal à mentir sur son âge ?',
  'Qui écoute une chanson en boucle jusqu\'à la détester ?',
  'Qui range ses affaires en les cachant quelque part ?',
  'Qui gagnerait à un concours de « qui reste sérieux le plus longtemps » ?',
  'Qui relit le plus souvent les vieux messages ?'
];

/* --- « Tu préfères » : la question porte sur UN des deux, l'autre
       doit deviner sa réponse --- */
const PREFERE = [
  ['Repartir de zéro dans une ville inconnue', 'Rester toute sa vie au même endroit'],
  ['Ne plus jamais avoir mal aux jambes', 'Ne plus jamais être fatigué'],
  ['Un week-end en forêt sans réseau', 'Un week-end en ville avec tout ouvert'],
  ['Savoir exactement quand on va mourir', 'Ne jamais savoir'],
  ['Pouvoir voler mais lentement', 'Courir très vite mais au sol'],
  ['Perdre toutes ses photos', 'Perdre toute sa musique'],
  ['Être en avance d\'une heure partout', 'Être en retard de dix minutes partout'],
  ['Dormir douze heures d\'affilée', 'Ne plus jamais avoir besoin de dormir'],
  ['Avoir un chien qui parle', 'Avoir un chat qui comprend tout'],
  ['Ne manger que du salé', 'Ne manger que du sucré'],
  ['Vivre sans musique', 'Vivre sans films'],
  ['Être toujours le premier levé', 'Être toujours le dernier couché'],
  ['Recevoir une lettre par semaine', 'Recevoir un appel par jour'],
  ['Se souvenir de tout, même du pire', 'Oublier facilement, même le meilleur'],
  ['Un très grand appartement en ville', 'Une petite maison avec un jardin'],
  ['Passer une journée entière au lit', 'Passer une journée entière dehors'],
  ['Savoir tout réparer', 'Savoir tout cuisiner'],
  ['Un anniversaire avec vingt personnes', 'Un anniversaire à deux'],
  ['Ne plus jamais avoir froid', 'Ne plus jamais avoir peur'],
  ['Être connu de tout le monde', 'Être compris par une seule personne'],
  ['Voyager en train pendant douze heures', 'Prendre l\'avion deux heures'],
  ['Devoir tout dire à voix haute', 'Ne pouvoir écrire que des messages'],
  ['Avoir toujours raison mais seul', 'Avoir souvent tort mais bien entouré'],
  ['Refaire une journée parfaite en boucle', 'Ne jamais revivre deux fois la même'],
  ['Un métier passionnant très prenant', 'Un métier tranquille avec du temps libre'],
  ['Pouvoir parler toutes les langues', 'Pouvoir jouer de tous les instruments'],
  ['Un chien énorme', 'Trois petits chiens'],
  ['Ne plus jamais repasser', 'Ne plus jamais passer l\'aspirateur'],
  ['Vivre au bord d\'un lac', 'Vivre au bord de l\'océan'],
  ['Être surpris tout le temps', 'Tout prévoir à l\'avance'],
  ['Rire aux larmes une fois par jour', 'Ne plus jamais être triste'],
  ['Une nuit sous les étoiles', 'Une nuit dans un hôtel de luxe'],
  ['Pouvoir revenir un jour en arrière', 'Pouvoir voir un jour en avant'],
  ['Manger le même plat parfait chaque jour', 'Manger différent mais moyen'],
  ['Un ami qui dit toujours la vérité', 'Un ami qui ment pour te protéger'],
  ['Ne plus jamais attendre', 'Ne plus jamais te presser'],
  ['Perdre la notion du temps', 'Perdre le sens de l\'orientation'],
  ['Faire le tour du monde seul', 'Rester chez toi avec tout le monde'],
  ['Un feu de cheminée en hiver', 'Un orage regardé de la fenêtre'],
  ['Danser très mal devant tout le monde', 'Chanter très mal devant une personne'],
  ['Une vie calme et prévisible', 'Une vie fatigante mais pleine d\'histoires'],
  ['Savoir ce que les gens pensent de toi', 'Ne jamais rien en savoir'],
  ['Passer un mois sans écran', 'Passer un mois sans sortir'],
  ['Être vieux et amoureux', 'Être jeune et libre']
];

/* --- Le quiz du chapiteau : bataille de vitesse.
       [question, [4 réponses], index de la bonne] --- */
const QUIZ = [
  ['Combien de cordes a un violon ?', ['4', '5', '6', '3'], 0],
  ['Quel animal est le plus rapide sur terre ?', ['Le guépard', 'Le lion', 'L\'autruche', 'Le lévrier'], 0],
  ['Dans quel pays est né le cirque moderne ?', ['Angleterre', 'Italie', 'France', 'Russie'], 0],
  ['Combien de minutes dans une journée ?', ['1440', '1200', '2400', '960'], 0],
  ['Quelle est la plus grande planète du système solaire ?', ['Jupiter', 'Saturne', 'Neptune', 'Uranus'], 0],
  ['Que mesure un décibel ?', ['Le son', 'La lumière', 'La chaleur', 'La vitesse'], 0],
  ['Combien d\'ailes a une abeille ?', ['4', '2', '6', '8'], 0],
  ['Quel pays a la plus longue côte du monde ?', ['Le Canada', 'La Russie', 'L\'Australie', 'Le Brésil'], 0],
  ['Qui a peint « La Nuit étoilée » ?', ['Van Gogh', 'Monet', 'Picasso', 'Dalí'], 0],
  ['Combien de touches a un piano classique ?', ['88', '76', '64', '96'], 0],
  ['Quel est l\'os le plus long du corps ?', ['Le fémur', 'Le tibia', 'L\'humérus', 'Le radius'], 0],
  ['En quelle année a eu lieu le premier pas sur la Lune ?', ['1969', '1961', '1972', '1958'], 0],
  ['Quelle mer est la plus salée ?', ['La mer Morte', 'La mer Rouge', 'La Baltique', 'La Méditerranée'], 0],
  ['Combien de joueurs dans une équipe de volley ?', ['6', '5', '7', '11'], 0],
  ['Quel métal remplit surtout les câbles électriques ?', ['Le cuivre', 'Le fer', 'L\'or', 'Le plomb'], 0],
  ['Quelle est la capitale de l\'Australie ?', ['Canberra', 'Sydney', 'Melbourne', 'Perth'], 0],
  ['De quelle couleur est le sang d\'une pieuvre ?', ['Bleu', 'Rouge', 'Vert', 'Transparent'], 0],
  ['Qui a écrit « Le Petit Prince » ?', ['Saint-Exupéry', 'Camus', 'Verne', 'Pagnol'], 0],
  ['Quel est le plus grand désert du monde ?', ['L\'Antarctique', 'Le Sahara', 'Le Gobi', 'L\'Atacama'], 0],
  ['Combien de temps met la lumière du Soleil à nous atteindre ?', ['8 minutes', '1 seconde', '1 heure', '30 minutes'], 0],
  ['Quel animal ne peut pas sauter ?', ['L\'éléphant', 'Le rhinocéros', 'L\'hippopotame', 'La girafe'], 0],
  ['Quelle est la monnaie du Japon ?', ['Le yen', 'Le won', 'Le yuan', 'Le baht'], 0],
  ['Combien d\'États composent les États-Unis ?', ['50', '48', '52', '49'], 0],
  ['Quelle ville est traversée par le Bosphore ?', ['Istanbul', 'Athènes', 'Le Caire', 'Beyrouth'], 0],
  ['De quoi est faite la barbe à papa ?', ['De sucre', 'De farine', 'De lait', 'De miel'], 0],
  ['Quel fruit contient le plus d\'eau ?', ['La pastèque', 'La pomme', 'L\'orange', 'Le raisin'], 0],
  ['Combien de dents a un adulte ?', ['32', '28', '30', '36'], 0],
  ['Quel océan borde Lacanau ?', ['L\'Atlantique', 'La Méditerranée', 'La Manche', 'La mer du Nord'], 0],
  ['Quelle est la vitesse du son dans l\'air ?', ['340 m/s', '150 m/s', '900 m/s', '30 m/s'], 0],
  ['Quel gaz respirons-nous majoritairement ?', ['L\'azote', 'L\'oxygène', 'Le CO₂', 'L\'hydrogène'], 0],
  ['Combien de cœurs a une pieuvre ?', ['3', '1', '2', '4'], 0],
  ['Quel est le plus haut sommet de France ?', ['Le mont Blanc', 'Le Pic du Midi', 'La Barre des Écrins', 'Le Puy de Dôme'], 0],
  ['Que fabrique une abeille en plus du miel ?', ['De la cire', 'Du sucre', 'De la résine', 'Du coton'], 0],
  ['Combien de cartes dans un jeu de 52 sans les jokers ?', ['52', '54', '48', '56'], 0],
  ['Quel est l\'animal emblème du cirque avec le lion ?', ['L\'éléphant', 'Le loup', 'Le cerf', 'Le renard'], 0],
  ['Quelle est la langue la plus parlée au monde ?', ['Le mandarin', 'L\'anglais', 'L\'espagnol', 'L\'hindi'], 0],
  ['Combien de jours dure une année bissextile ?', ['366', '365', '364', '367'], 0],
  ['Quel fleuve traverse Bordeaux ?', ['La Garonne', 'La Dordogne', 'L\'Adour', 'La Charente'], 0],
  ['Que soigne un ophtalmologue ?', ['Les yeux', 'Les dents', 'La peau', 'Le cœur'], 0],
  ['Combien de cases sur un échiquier ?', ['64', '81', '100', '49'], 0],
  ['Quel est le contraire de « éphémère » ?', ['Durable', 'Fragile', 'Rapide', 'Léger'], 0],
  ['Quelle note vient après le sol ?', ['La', 'Fa', 'Si', 'Ré'], 0],
  ['Combien d\'anneaux sur le drapeau olympique ?', ['5', '4', '6', '7'], 0],
  ['Quel animal dort debout ?', ['Le cheval', 'Le chien', 'Le chat', 'Le lapin'], 0],
  ['Quelle est la capitale de la Norvège ?', ['Oslo', 'Stockholm', 'Helsinki', 'Copenhague'], 0],
  ['Combien de temps dure une année-lumière ?', ['Ce n\'est pas une durée', 'Un an', 'Mille ans', 'Un siècle'], 0],
  ['Quel instrument a des touches noires et blanches ?', ['Le piano', 'La harpe', 'Le violon', 'La flûte'], 0],
  ['Que mange un herbivore ?', ['Des plantes', 'De la viande', 'Des insectes', 'Du poisson'], 0]
];
