/* =========================================================
   LE PONT — les questions
   Formulées sans pronom, pour se lire pareil des deux côtés :
   l'un voit « TOI — … », l'autre voit « STACY — … ».
   Rien n'est repris de /duo/ ni de /cirque/.
   ========================================================= */

/* --- DEVINE : l'un répond pour lui, l'autre devine sa réponse.
       [ question, [quatre réponses] ] --- */
const DEVINE = [
  ['Ce qui manque le plus quand on est loin', ['Sa voix', 'Ses bras', 'Son odeur', 'Sa présence à côté, sans rien dire']],
  ['Le tout premier geste en se retrouvant', ['Un câlin qui n\'en finit pas', 'Un baiser', 'Se regarder sans rien dire', 'Sauter dessus']],
  ['Le moment de la journée où on pense le plus à l\'autre', ['Au réveil', 'Dans les transports', 'Au moment de manger', 'Juste avant de dormir']],
  ['Ce qu\'on relit le plus souvent', ['Les vieux messages', 'Les photos', 'Rien, on préfère se souvenir', 'Les vocaux']],
  ['La chanson qui fait penser à l\'autre', ['Une chanson douce', 'Une chanson qu\'on a écoutée ensemble', 'Une chanson triste', 'Une chanson qu\'on a chantée fort en voiture']],
  ['Ce qui fait craquer le plus chez l\'autre', ['Son rire', 'Ses yeux', 'Sa façon de parler', 'Sa maladresse']],
  ['Le pire moment de la distance', ['Le soir', 'Le dimanche', 'Après un appel', 'Quand tout va mal et qu\'on est seul']],
  ['Ce qu\'on ferait d\'un après-midi entier ensemble', ['Ne rien faire, collés', 'Sortir marcher', 'Cuisiner un truc', 'Regarder trois films d\'affilée']],
  ['Ce qu\'on garde précieusement', ['Une photo', 'Un vêtement', 'Un message', 'Un objet donné']],
  ['Ce qui rassure le plus dans un message', ['« Je pense à toi »', 'Un bonjour le matin', 'Un vocal', 'Une photo au hasard']],
  ['La première chose qu\'on remarque sur une photo de l\'autre', ['Le sourire', 'Les yeux', 'Les cheveux', 'Le décor autour']],
  ['Ce qui énerve le plus, en vrai', ['Les réponses trop courtes', 'Attendre une réponse', 'Les silences', 'Rien, jamais']],
  ['Le cadeau qui ferait le plus plaisir', ['Une lettre écrite à la main', 'Une photo imprimée', 'Un truc fait maison', 'Une surprise le jour même']],
  ['La saison qu\'on préfère à deux', ['L\'été', 'L\'automne', 'L\'hiver sous une couverture', 'Le printemps']],
  ['Ce qu\'on veut entendre après une mauvaise journée', ['« Raconte-moi »', '« Je suis là »', 'Rien, juste un appel', '« Viens là »']],
  ['Le film qu\'on regarderait ensemble ce soir', ['Un truc qui fait peur', 'Une comédie', 'Un truc qui fait pleurer', 'Un dessin animé']],
  ['L\'endroit rêvé pour partir tous les deux', ['Au bord de la mer', 'À la montagne', 'Dans une grande ville', 'N\'importe où, mais loin']],
  ['Ce qu\'on préfère faire au réveil ensemble', ['Rester au lit une heure de plus', 'Un vrai petit-déjeuner', 'Sortir tôt', 'Se rendormir']],
  ['Ce qui manque le plus dans un appel', ['Le toucher', 'Le silence partagé', 'Voir ses réactions', 'La chaleur']],
  ['La preuve d\'amour qui touche le plus', ['Se souvenir d\'un détail', 'Faire de la route', 'Écrire quelque chose', 'Être là au bon moment']],
  ['Ce qu\'on ferait s\'il restait une heure ensemble', ['Un câlin, tout du long', 'Parler de tout', 'Sortir marcher', 'Prendre des photos']],
  ['Ce qui fait le plus rire chez l\'autre', ['Ses grimaces', 'Ses bêtises', 'Sa mauvaise foi', 'Sa voix quand il imite quelqu\'un']],
  ['Le petit surnom préféré', ['Mon cœur', 'Mon bébé', 'Mon chat', 'Mon amour']],
  ['Ce qu\'on préfère recevoir sans prévenir', ['Un appel', 'Une photo', 'Un vocal', 'Une commande à manger']],
  ['Ce qui manque le plus le dimanche', ['Traîner ensemble', 'Manger ensemble', 'Ne rien faire à deux', 'Sortir marcher']],
  ['L\'animal qu\'on aurait ensemble en plus', ['Un autre chien', 'Un chat', 'Un truc bizarre', 'Aucun, ça suffit']],
  ['Ce qui ferait le plus plaisir un soir de semaine', ['Un appel long', 'Regarder un truc ensemble à distance', 'Jouer ensemble', 'Dormir en appel']],
  ['La qualité qu\'on admire le plus chez l\'autre', ['Sa patience', 'Sa gentillesse', 'Sa force', 'Sa façon de ne rien lâcher']],
  ['Le souvenir à deux le plus fort', ['La première fois', 'Un fou rire', 'Une nuit entière à parler', 'Un départ difficile']],
  ['Ce qu\'on ferait en premier dans un appartement à deux', ['Tout ranger', 'Ne rien faire', 'Cuisiner', 'Se poser dans le canapé']],
  ['Ce qui fait le plus peur', ['S\'habituer à la distance', 'Ne pas être assez présent', 'Décevoir l\'autre', 'Que ça devienne normal']],
  ['La façon préférée de dire je t\'aime', ['Le dire', 'Le montrer', 'L\'écrire', 'Le faire deviner']],
  ['Ce qu\'on emporterait de l\'autre si on pouvait', ['Son pull', 'Son parfum', 'Sa voix', 'Ses mains']],
  ['Le pire défaut assumé', ['Trop bouder', 'Trop parler', 'Ne rien dire quand ça va mal', 'Être trop tête en l\'air']],
  ['L\'heure préférée pour s\'appeler', ['Le matin tôt', 'L\'après-midi', 'Le soir', 'Très tard, quand tout est calme']],
  ['Ce qui compte le plus, au fond', ['Se sentir choisi', 'Se sentir compris', 'Se sentir attendu', 'Se sentir en sécurité']]
];

/* --- OUI OU NON : l'un répond sincèrement, l'autre devine --- */
const OUINON = [
  'Relire vos vieux messages en cachette : déjà fait ?',
  'Avoir gardé un objet qui vient de l\'autre sur soi toute une journée : déjà fait ?',
  'Avoir pleuré à cause de la distance : déjà arrivé ?',
  'Avoir compté les jours qui restent avant de se revoir : déjà fait ?',
  'S\'être endormi pendant un appel : déjà arrivé ?',
  'Avoir parlé de l\'autre à quelqu\'un qui s\'en fichait complètement : déjà fait ?',
  'Avoir regardé les photos de l\'autre au milieu de la nuit : déjà fait ?',
  'Avoir répété dans sa tête ce qu\'on allait dire avant d\'appeler : déjà fait ?',
  'Avoir menti en disant « ça va » alors que non : déjà fait ?',
  'Avoir imaginé la scène des retrouvailles en détail : déjà fait ?',
  'Avoir gardé un message sans y répondre juste pour le relire : déjà fait ?',
  'Avoir eu envie de prendre un train sur un coup de tête : déjà arrivé ?',
  'Avoir mis une chanson en boucle en pensant à l\'autre : déjà fait ?',
  'Avoir écrit un message puis tout effacé sans l\'envoyer : déjà fait ?',
  'S\'être disputé pour une bêtise et l\'avoir regretté dans la minute : déjà arrivé ?',
  'Avoir dormi avec quelque chose qui appartient à l\'autre : déjà fait ?',
  'Avoir eu peur d\'être de trop : déjà arrivé ?',
  'Avoir souri tout seul en pleine rue à cause d\'un message : déjà fait ?',
  'Avoir gardé une capture d\'écran d\'une conversation : déjà fait ?',
  'Avoir refusé une sortie pour rester disponible : déjà fait ?',
  'Avoir imaginé à quoi ressemblerait votre appartement : déjà fait ?',
  'Avoir eu envie de dire quelque chose d\'important et s\'être dégonflé : déjà arrivé ?',
  'Avoir prévu une surprise puis tout raconté avant : déjà fait ?',
  'Avoir attendu un message en regardant le téléphone toutes les deux minutes : déjà fait ?',
  'Avoir eu un fou rire tout seul en repensant à un truc de nous : déjà fait ?',
  'Avoir choisi un vêtement en pensant à ce que l\'autre en dirait : déjà fait ?',
  'Avoir gardé un ticket, un papier, un truc sans valeur : déjà fait ?',
  'Avoir voulu appeler juste pour entendre la voix, sans rien à dire : déjà fait ?',
  'Avoir été jaloux sans le montrer : déjà arrivé ?',
  'Avoir raconté un rêve où l\'autre était dedans : déjà fait ?',
  'Avoir eu envie de tout arrêter, une seconde, un jour de fatigue : déjà arrivé ?',
  'Avoir relu une lettre ou un message plus de dix fois : déjà fait ?',
  'Avoir appris un truc juste parce que ça intéresse l\'autre : déjà fait ?',
  'Avoir pensé « c\'est elle » ou « c\'est lui » très tôt : déjà arrivé ?'
];

/* --- ENSEMBLE : on désigne un nom, on marque si c'est le même --- */
const ENSEMBLE = [
  'Qui de nous deux dit « je t\'aime » le plus souvent ?',
  'Qui de nous deux craque le premier après une dispute ?',
  'Qui de nous deux attend le plus les appels ?',
  'Qui de nous deux est le plus démonstratif ?',
  'Qui de nous deux a le plus peur de perdre l\'autre ?',
  'Qui de nous deux prévoit le plus les retrouvailles ?',
  'Qui de nous deux est le plus patient ?',
  'Qui de nous deux boude le plus longtemps ?',
  'Qui de nous deux ferait le plus de route pour l\'autre ?',
  'Qui de nous deux garde le plus de souvenirs matériels ?',
  'Qui de nous deux dort le mieux quand l\'autre n\'est pas là ?',
  'Qui de nous deux parle le plus de l\'autre à ses proches ?',
  'Qui de nous deux a le plus de mal à dire ce qui ne va pas ?',
  'Qui de nous deux rassure le mieux ?',
  'Qui de nous deux est le plus jaloux ?',
  'Qui de nous deux a le plus changé depuis le début ?',
  'Qui de nous deux offre les cadeaux les plus réfléchis ?',
  'Qui de nous deux tiendrait le plus longtemps sans donner de nouvelles ?',
  'Qui de nous deux est le plus romantique en secret ?',
  'Qui de nous deux prend le plus de photos de l\'autre ?',
  'Qui de nous deux s\'excuse en premier ?',
  'Qui de nous deux a le plus besoin de mots ?',
  'Qui de nous deux a le plus besoin de gestes ?',
  'Qui de nous deux serait le plus perdu tout seul ?',
  'Qui de nous deux fait le plus rire l\'autre ?',
  'Qui de nous deux a la plus mauvaise foi ?',
  'Qui de nous deux pense le plus à l\'avenir ?',
  'Qui de nous deux vit le plus au jour le jour ?',
  'Qui de nous deux remarque le premier que l\'autre ne va pas bien ?',
  'Qui de nous deux a le plus de mal à raccrocher ?',
  'Qui de nous deux ferait la plus grosse surprise ?',
  'Qui de nous deux dit le plus souvent « c\'est toi qui choisis » ?',
  'Qui de nous deux est le plus câlin ?',
  'Qui de nous deux a le plus confiance en nous deux ?'
];

/* --- SUR DIX : l'un se note, l'autre devine sa note --- */
const SURDIX = [
  'Supporter la distance en ce moment',
  'Avoir hâte des prochaines retrouvailles',
  'Se sentir compris par l\'autre',
  'Être doué pour les surprises',
  'Être jaloux, honnêtement',
  'Savoir dire ce qu\'on ressent',
  'Se sentir chanceux d\'être avec l\'autre',
  'Être patient quand l\'autre ne répond pas',
  'Aimer les gestes romantiques',
  'Croire à ce que ça donnera dans dix ans',
  'Être fatigué par la vie en ce moment',
  'Se sentir attendu',
  'Oser demander de l\'attention',
  'Trouver que l\'autre en fait assez',
  'Se trouver drôle',
  'Avoir peur de mal faire',
  'Aimer parler de l\'avenir',
  'Savoir garder un secret',
  'Se sentir en sécurité dans cette relation',
  'Avoir envie de tout plaquer pour se rejoindre',
  'Être quelqu\'un de facile à vivre',
  'Être doué pour consoler'
];
